/**
 * Per|Form NFL Draft Data — 2026 NFL Draft
 *
 * Type definitions and production arrays for draft prospects,
 * redraft analysis, and NFL team needs.
 *
 * Timeline (Feb 2026):
 *   - 2024 NFL Draft class → now in 2nd NFL season (see REDRAFT_2024_CLASS)
 *   - 2025 NFL Draft class → just completed rookie season (see REDRAFT_2025_CLASS)
 *   - 2026 NFL Draft class → upcoming (April 23-25 in Pittsburgh)
 *
 * Sources: Daniel Jeremiah top 50, Mel Kiper mock 2.0, CBS Sports,
 *          PFF Big Board, Tankathon, ESPN draft order.
 *
 * NOTE: Jeremiah Smith (WR, Ohio State) is NOT eligible for the 2026 draft.
 * He returns to Ohio State for 2026 season and will be eligible for 2027.
 *
 * Tiers:
 *   TOP_5     — Consensus top 5 pick
 *   TOP_15    — First half of round 1
 *   FIRST_ROUND — Late round 1
 *   DAY_2     — Rounds 2-3
 *   DAY_3     — Rounds 4-7
 *   PRIORITY_UDFA — Top undrafted free agents
 *   UDFA      — Undrafted free agent
 */

export interface SeedDraftProspect {
  firstName: string;
  lastName: string;
  position: string;
  college: string;
  conference?: string;
  classYear: string;
  eligibility?: string;
  height?: string;
  weight?: number;
  paiScore: number;
  tier: string;
  performance: number;
  athleticism: number;
  intangibles: number;
  overallRank: number;
  positionRank: number;
  trend: string;
  scoutMemo?: string;
  tags?: string;
  comparisons?: string;
  collegeStats?: string;
  combineInvite?: boolean;
  seniorBowl?: boolean;
  projectedRound?: number;
  projectedPick?: number;
  projectedTeam?: string;
  bullCase?: string;
  bearCase?: string;
  mediationVerdict?: string;
  debateWinner?: string;
  enrichedBy?: string;
  // Combine measurables
  armLength?: string;
  handSize?: string;
  fortyYard?: number;
  tenYardSplit?: number;
  benchPress?: number;
  verticalJump?: number;
  broadJump?: number;
  threeCone?: number;
  shuttle?: number;
  combineGrade?: 'STOCK_UP' | 'STOCK_DOWN' | 'AS_EXPECTED' | 'DID_NOT_PARTICIPATE';
  combineNotes?: string;
}

/** Position group for Combine workout days */
export type CombinePositionGroup =
  | 'DL_EDGE_LB'   // Day 1 — Feb 26
  | 'DB_TE'         // Day 2 — Feb 27
  | 'QB_RB_WR'      // Day 3 — Feb 28
  | 'OL';           // Day 4 — Mar 1

export const COMBINE_POSITION_GROUPS: Record<CombinePositionGroup, {
  label: string;
  date: string;
  positions: string[];
}> = {
  DL_EDGE_LB: { label: 'DL / EDGE / LB', date: 'Feb 26', positions: ['DL', 'EDGE', 'DT', 'DE', 'LB', 'ILB', 'OLB'] },
  DB_TE: { label: 'DB / TE', date: 'Feb 27', positions: ['CB', 'S', 'FS', 'SS', 'DB', 'TE'] },
  QB_RB_WR: { label: 'QB / RB / WR', date: 'Feb 28', positions: ['QB', 'RB', 'WR', 'ATH'] },
  OL: { label: 'OL', date: 'Mar 1', positions: ['OT', 'OG', 'C', 'IOL', 'OL'] },
};

/** NFL Team needs for the 2026 draft */
export interface SeedNFLTeamNeeds {
  teamName: string;
  abbreviation: string;
  city: string;
  conference: string;
  division: string;
  record?: string;
  draftOrder: number;
  needs: string;
  capSpace?: string;
  keyFAs?: string;
  projectedPick?: string;
}

// ─────────────────────────────────────────────────────────────
// 2026 NFL Draft Prospects — populate via POST /api/perform/draft
// April 23-25 in Pittsburgh (Acrisure Stadium & Point State Park)
// ─────────────────────────────────────────────────────────────

export const SEED_DRAFT_PROSPECTS: SeedDraftProspect[] = [
  // ─── TOP 5 ─────────────────────────────────────────────────
  {
    firstName: 'Fernando',
    lastName: 'Mendoza',
    position: 'QB',
    college: 'Indiana',
    conference: 'Big Ten',
    classYear: 'Senior',
    eligibility: 'RS-Senior',
    height: '6-5',
    weight: 225,
    paiScore: 97,
    tier: 'TOP_5',
    performance: 98,
    athleticism: 91,
    intangibles: 97,
    overallRank: 1,
    positionRank: 1,
    trend: 'STEADY',
    scoutMemo: '2025 Heisman Trophy winner and CFP National Champion. Led Indiana to its first-ever national title. Led FBS with 41 TDs and 3,535 yards on 72.3% completion with 89.5 QBR. Consensus #1 overall pick at -8000 odds — lock for the Raiders.',
    tags: 'Heisman,National Champion,Pro-Ready,Accurate,Leader',
    comparisons: 'Joe Burrow,Andrew Luck',
    collegeStats: '{"completionPct":"72.3%","passingYards":"3535","passingTDs":"41","interceptions":"6","qbr":"89.5"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 1,
    projectedTeam: 'LV',
    // Combine: Will NOT throw at combine — waiting for pro day April 1
    armLength: '33 1/4"',
    handSize: '10 1/8"',
    combineGrade: 'AS_EXPECTED',
    combineNotes: 'Did not throw at combine. Interviewed with Raiders, spoke highly of Tom Brady. Waiting for Indiana pro day April 1. Measured 6-4 5/8, 222 lbs. Still consensus #1.',
    bullCase: 'Franchise QB from Day 1. National championship pedigree, elite accuracy, and command of the offense. The most pro-ready QB in the class by a wide margin.',
    bearCase: 'Indiana program historically not an NFL pipeline. One elite season — can he sustain it at the next level? Arm strength is good but not special.',
    mediationVerdict: 'Bull case wins. Championship performance + elite production + accuracy = franchise QB.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Arvell',
    lastName: 'Reese',
    position: 'LB',
    college: 'Ohio State',
    conference: 'Big Ten',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '6-4',
    weight: 243,
    paiScore: 96,
    tier: 'TOP_5',
    performance: 97,
    athleticism: 96,
    intangibles: 95,
    overallRank: 2,
    positionRank: 1,
    trend: 'STEADY',
    scoutMemo: 'Consensus All-American. Jumps off the Ohio State tape. 69 tackles, 9 TFL, 6.5 sacks in 2025. Hyper-elite explosiveness and cornering ability. CBS Sports: "the NFL version of a lottery pick" with all the traits to be an elite pass rusher.',
    tags: 'Versatile,Pass Rush,Instincts,Ohio State,Lottery Pick',
    comparisons: 'Micah Parsons,Patrick Queen',
    collegeStats: '{"sacks":"6.5","TFLs":"9","tackles":"69","runStops":"9","pressures":"42"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 2,
    projectedTeam: 'NYJ',
    // Combine Day 1 — Feb 26 (DL/EDGE/LB)
    fortyYard: 4.46,
    tenYardSplit: 1.56,
    combineGrade: 'STOCK_UP',
    combineNotes: 'Tied for fastest LB 40 at 4.46s. At 6-4, 243 lbs, his speed is elite. Top-2 pick solidified.',
    bullCase: 'Most versatile defensive player in the class. Can rush, cover, and stuff the run. Day 1 impact player at multiple positions.',
    bearCase: 'True position in the NFL unclear — is he a 3-4 OLB, 4-3 DE, or off-ball LB? Tweener risk.',
    mediationVerdict: 'Bull case wins. Versatility is a feature in modern NFL defenses, not a bug.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'David',
    lastName: 'Bailey',
    position: 'EDGE',
    college: 'Texas Tech',
    conference: 'Big 12',
    classYear: 'Junior',
    eligibility: 'RS-Junior',
    height: '6-4',
    weight: 251,
    paiScore: 95,
    tier: 'TOP_5',
    performance: 96,
    athleticism: 95,
    intangibles: 94,
    overallRank: 3,
    positionRank: 1,
    trend: 'UP',
    scoutMemo: 'Led the nation with 14.5 sacks and 19.5 TFL in 2025. All-American. Bench 405, squat 550, top speed 22.16 mph. Rare combination of power and athleticism off the edge. Top-3 lock.',
    tags: 'Speed Rush,Bend,First Step,Elite,Closer',
    comparisons: 'Myles Garrett,Von Miller',
    collegeStats: '{"sacks":"14.5","TFLs":"19.5","tackles":"56","forcedFumbles":"3","pressures":"52"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 3,
    projectedTeam: 'ARI',
    // Combine Day 1 — Feb 26 (DL/EDGE/LB)
    fortyYard: 4.50,
    tenYardSplit: 1.57,
    verticalJump: 35.0,
    broadJump: 129,
    combineGrade: 'STOCK_UP',
    combineNotes: 'Fastest DL 40 at 4.50s. Testing numbers comparable to Von Miller (No. 2 pick, 2011). Confirmed elite athlete. 35" vertical, 10\'9" broad at 251 lbs.',
    bullCase: 'Best pure edge rusher in the class. Pass rush is the most valuable defensive commodity. His get-off and closing speed are elite.',
    bearCase: 'Texas Tech competition level — did he face top OTs regularly? Needs to add weight for NFL.',
    mediationVerdict: 'Bull case wins. The pass rush production transcends conference strength concerns.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Caleb',
    lastName: 'Downs',
    position: 'S',
    college: 'Ohio State',
    conference: 'Big Ten',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '6-0',
    weight: 205,
    paiScore: 95,
    tier: 'TOP_5',
    performance: 96,
    athleticism: 94,
    intangibles: 96,
    overallRank: 4,
    positionRank: 1,
    trend: 'STEADY',
    scoutMemo: 'Jim Thorpe Award and Lott Trophy winner. 93.6 career PFF grade. 67 tackles, 5 TFL, 2 INT, 1 sack in 2025. Brother of NFL WR Josh Downs, son of former NFL RB Gary Downs. Elite in coverage and run support. Would be highest safety drafted since Eric Turner went #2 in 1991.',
    tags: 'Jim Thorpe,Lott Trophy,Range,Football IQ,Ohio State',
    comparisons: 'Derwin James,Ed Reed (ceiling)',
    collegeStats: '{"interceptions":"2","passBreakups":"11","tackles":"67","forcedFumbles":"2","TFLs":"5","pffGrade":"93.6"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 5,
    projectedTeam: 'CAR',
    // Combine Day 2 — Feb 27 (DB/TE)
    combineGrade: 'AS_EXPECTED',
    combineNotes: 'Top-5 talent regardless of testing. PFF\'s top player on their board. Mock draft range spans No. 2 to mid-first round due to positional value debate, not talent.',
    bullCase: 'Best safety prospect since Derwin James. Football DNA runs in his blood. Will transform any secondary from Day 1.',
    bearCase: 'Safety is not a premium draft position historically. Some teams will pass on a safety this high despite the talent.',
    mediationVerdict: 'Bull case wins. Transcendent safety talent justifies the premium pick.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Rueben',
    lastName: 'Bain Jr.',
    position: 'EDGE',
    college: 'Miami',
    conference: 'ACC',
    classYear: 'Junior',
    eligibility: 'RS-Junior',
    height: '6-2 1/4',
    weight: 263,
    paiScore: 94,
    tier: 'TOP_5',
    performance: 95,
    athleticism: 93,
    intangibles: 94,
    overallRank: 5,
    positionRank: 2,
    trend: 'DOWN',
    scoutMemo: '93.1 PFF grade (2nd among all defenders). 46 tackles, 16.5 TFL, 8.5 sacks, 80 total pressures (2nd nationally). Versatile build — can play 3-4 DE to 4-3 OLB. Powerful hands. Concern: 30 7/8" arm length (4th shortest for EDGE since 1999).',
    tags: 'Power,Versatile Build,Motor,Miami,Pressures',
    comparisons: 'Cameron Jordan,Calais Campbell',
    collegeStats: '{"sacks":"8.5","TFLs":"16.5","tackles":"46","forcedFumbles":"3","pressures":"80","pffGrade":"93.1"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 4,
    projectedTeam: 'TEN',
    // Combine Day 1 — Feb 26 (DL/EDGE/LB)
    armLength: '30 7/8"',
    handSize: '10 1/4"',
    combineGrade: 'STOCK_DOWN',
    combineNotes: 'Did NOT do athletic testing or on-field drills. 30 7/8" arms (4th shortest EDGE since 1999), 77 3/8" wingspan creating projection risk. Stock slipping with other EDGEs excelling.',
    bullCase: 'Scheme-versatile defender who can play multiple techniques. His power and motor make him a 10-year starter. PFF\'s #1 overall prospect.',
    bearCase: 'Short arms, did not test athletically at combine. Other edge rushers outperformed him. May slip from top 5.',
    mediationVerdict: 'Split. Talent is undeniable but combine absence and short arms are real concerns.',
    debateWinner: 'SPLIT',
  },

  // ─── TOP 15 ────────────────────────────────────────────────
  {
    firstName: 'Carnell',
    lastName: 'Tate',
    position: 'WR',
    college: 'Ohio State',
    conference: 'Big Ten',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '6-3',
    weight: 195,
    paiScore: 94,
    tier: 'TOP_15',
    performance: 95,
    athleticism: 93,
    intangibles: 93,
    overallRank: 6,
    positionRank: 1,
    trend: 'STEADY',
    scoutMemo: 'Former 5-star recruit. 51 receptions, 875 yards, 9 TDs in 2025. Averaged 17.2 YPC. Elite body control, precise route runner with great hands. Outstanding size/speed blend at 6-3. Willingness to block sets him apart.',
    tags: 'Route Runner,Hands,Body Control,Ohio State,Complete WR',
    comparisons: 'Davante Adams,Amari Cooper',
    collegeStats: '{"receptions":"51","receivingYards":"875","receivingTDs":"9","yardsPerCatch":"17.2"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 6,
    projectedTeam: 'CLE',
    // Combine Day 3 — Feb 28 (QB/RB/WR)
    combineGrade: 'AS_EXPECTED',
    combineNotes: 'WR1 in the class. Outstanding size/speed combo at 6-3. Expected to test well in 40 and route-running drills. Elite body control confirmed in on-field work.',
    bullCase: 'Most complete WR in the class. Route running, hands, body control, and blocking all grade out as elite. Immediate WR1.',
    bearCase: 'Played alongside Jeremiah Smith — will production hold as a true #1 with all the attention?',
    mediationVerdict: 'Bull case wins. His skill set is too refined to be scheme-dependent.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Spencer',
    lastName: 'Fano',
    position: 'OT',
    college: 'Utah',
    conference: 'Big 12',
    classYear: 'Junior',
    eligibility: 'RS-Junior',
    height: '6-6',
    weight: 308,
    paiScore: 94,
    tier: 'TOP_15',
    performance: 96,
    athleticism: 91,
    intangibles: 94,
    overallRank: 7,
    positionRank: 1,
    trend: 'STEADY',
    scoutMemo: '2025 Outland Trophy winner, First-Team All-American. 37 career games, 35 starts at both tackle spots. Allowed ZERO sacks in 2025 and just one in 2024. Quick feet and nimbleness belie his 308-lb frame. CBS: "cleanest OT in the class."',
    tags: 'Outland Trophy,Zero Sacks,Clean Technique,Utah,Both Tackle Spots',
    comparisons: 'Tristan Wirfs,Lane Johnson',
    collegeStats: '{"sacksAllowed":"0","gamesStarted":"27","penaltiesPerGame":"0.2","hitsAllowed":"3"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 7,
    projectedTeam: 'WAS',
    // Combine Day 4 — Mar 1 (OL)
    combineGrade: 'AS_EXPECTED',
    combineNotes: 'OL workouts Sunday Mar 1. Outland Trophy winner expected to confirm elite footwork. Already consensus top OT.',
    bullCase: 'Franchise tackle who provides elite pass protection immediately. Zero sacks allowed is a historic stat line.',
    bearCase: 'Played RT in college — can he transition to LT? Run blocking needs improvement against power rushers.',
    mediationVerdict: 'Bull case wins. Pass protection is paramount and he is the best at it.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Sonny',
    lastName: 'Styles',
    position: 'LB',
    college: 'Ohio State',
    conference: 'Big Ten',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '6-5',
    weight: 244,
    paiScore: 95,
    tier: 'TOP_15',
    performance: 93,
    athleticism: 99,
    intangibles: 92,
    overallRank: 8,
    positionRank: 2,
    trend: 'STEADY',
    scoutMemo: 'Versatile defensive weapon who has played safety, linebacker, and nickel at Ohio State. Elite athlete with rare size/speed combo. The ultimate Swiss Army knife defender.',
    tags: 'Versatile,Athlete,Size-Speed,Ohio State,Swiss Army Knife',
    comparisons: 'Kyle Hamilton,Isaiah Simmons',
    collegeStats: '{"tackles":"82","TFLs":"10","interceptions":"3","passBreakups":"7","sacks":"4"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 8,
    projectedTeam: 'KC',
    // Combine Day 1 — Feb 26 — STAR OF THE COMBINE
    fortyYard: 4.46,
    tenYardSplit: 1.56,
    verticalJump: 43.5,
    broadJump: 134,
    threeCone: 7.09,
    shuttle: 4.26,
    combineGrade: 'STOCK_UP',
    combineNotes: 'BEST COMBINE PERFORMANCE IN YEARS. First player since 2003 to run sub-4.5 40 with 40+ vertical and 11+ broad at 230+ lbs. 43.5" vertical is highest ever by a player 6-4+ tall. 9.99 RAS (Relative Athletic Score) — near perfect. Moving into top 5 conversation.',
    bullCase: 'Historic combine performance. Can play three positions at an elite level. Modern NFL covets this type of versatility. Kyle Hamilton 2.0 with even better testing.',
    bearCase: 'Jack of all trades, master of none? Teams may struggle to define his role, limiting his impact.',
    mediationVerdict: 'Bull case wins decisively after combine. Testing was cartoonish. Top-5 lock.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Jeremiyah',
    lastName: 'Love',
    position: 'RB',
    college: 'Notre Dame',
    conference: 'Independent',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '5-11',
    weight: 215,
    paiScore: 93,
    tier: 'TOP_15',
    performance: 95,
    athleticism: 94,
    intangibles: 90,
    overallRank: 9,
    positionRank: 1,
    trend: 'STEADY',
    scoutMemo: '2025 Doak Walker Award winner. 35 rushing TDs over 2024-2025 seasons. Sprinter speed (10.76s 100m). Led college football in touchdowns from scrimmage. DJ ranked him #2 overall. Best RB prospect in years.',
    tags: 'Doak Walker,Sprinter Speed,Touchdowns,Notre Dame,Three-Down Back',
    comparisons: 'Bijan Robinson,Saquon Barkley',
    collegeStats: '{"rushingYards":"1628","rushingTDs":"18","yardsPerCarry":"6.2","receptions":"42","receivingYards":"385","receivingTDs":"4","careerRushTDs":"35"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 9,
    projectedTeam: 'KC',
    // Combine Day 3 — Feb 28 (QB/RB/WR)
    combineGrade: 'AS_EXPECTED',
    combineNotes: 'RB workouts today Feb 28. Expected to showcase sprinter speed (10.76s 100m). Should test as one of the fastest RBs at the combine. Key day for his draft stock.',
    bullCase: 'True three-down back with elite receiving ability. Can be the centerpiece of an NFL offense. Kiper mocked him to KC in Round 1.',
    bearCase: 'RB positional value depresses his draft stock. History shows RBs taken this high rarely provide surplus value.',
    mediationVerdict: 'Bull case edges it. His receiving ability puts him in a different tier than pure runners.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Francis',
    lastName: 'Mauigoa',
    position: 'OT',
    college: 'Miami',
    conference: 'ACC',
    classYear: 'Junior',
    eligibility: 'RS-Junior',
    height: '6-5',
    weight: 320,
    paiScore: 92,
    tier: 'TOP_15',
    performance: 93,
    athleticism: 91,
    intangibles: 92,
    overallRank: 10,
    positionRank: 2,
    trend: 'STEADY',
    scoutMemo: 'ESPN consensus #1 OT in positional rankings. Physical mauler in the run game with improving pass protection. Miami OL anchor for two seasons.',
    tags: 'Run Blocker,Physical,Miami,Mauler,Anchor',
    comparisons: 'Penei Sewell,Rashawn Slater',
    collegeStats: '{"sacksAllowed":"2","gamesStarted":"28","penaltiesPerGame":"0.4"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 10,
    projectedTeam: 'CIN',
    // Combine Day 4 — Mar 1 (OL)
    combineGrade: 'AS_EXPECTED',
    combineNotes: 'OL workouts Sunday Mar 1. Physical mauler expected to confirm dominance in blocking drills.',
    bullCase: 'Most physical OT in the class. His run blocking is already NFL-caliber. Franchise left tackle upside.',
    bearCase: 'Pass protection technique needs refinement. Gets beat by speed rushers occasionally.',
    mediationVerdict: 'Bull case edges it. The physicality translates and the technique will come with NFL coaching.',
    debateWinner: 'BULL',
  },

  // ─── FIRST ROUND ───────────────────────────────────────────
  {
    firstName: 'Makai',
    lastName: 'Lemon',
    position: 'WR',
    college: 'USC',
    conference: 'Big Ten',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '5-11',
    weight: 195,
    paiScore: 92,
    tier: 'FIRST_ROUND',
    performance: 93,
    athleticism: 93,
    intangibles: 90,
    overallRank: 11,
    positionRank: 2,
    trend: 'UP',
    scoutMemo: 'Fred Biletnikoff Award winner. 79 receptions, 1,156 yards, 11 TDs in 2025. Unanimous All-American and First-Team All-Big Ten. DJ ranked him #7 overall. Precise route runner with excellent YAC ability.',
    tags: 'Biletnikoff,YAC,Unanimous AA,USC,Playmaker',
    comparisons: 'Amon-Ra St. Brown,Jaylen Waddle',
    collegeStats: '{"receptions":"79","receivingYards":"1156","receivingTDs":"11","yardsPerCatch":"14.6"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 11,
    projectedTeam: 'MIA',
    // Combine Day 3 — Feb 28 (QB/RB/WR)
    combineGrade: 'AS_EXPECTED',
    combineNotes: 'WR workouts today Feb 28. Biletnikoff Award winner expected to showcase speed and route-running. Should confirm top-15 status.',
    bullCase: 'Game-breaking speed and YAC ability. In the modern NFL, the slot is the most dangerous alignment. Instant offense.',
    bearCase: 'Undersized for the outside. Limited catch radius for contested catches. One-dimensional as an outside threat.',
    mediationVerdict: 'Bull case wins. Speed and YAC translate regardless of alignment.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Mansoor',
    lastName: 'Delane',
    position: 'CB',
    college: 'LSU',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '6-0',
    weight: 190,
    paiScore: 91,
    tier: 'FIRST_ROUND',
    performance: 92,
    athleticism: 92,
    intangibles: 90,
    overallRank: 12,
    positionRank: 1,
    trend: 'UP',
    scoutMemo: 'Virginia Tech transfer who dominated at LSU. 45 tackles, 11 PBU, 2 INT in 2025. Zero penalties and zero TDs allowed all season. 3.3 yards per target (4th nationally). True technician in man and zone.',
    tags: 'Zero TDs Allowed,Technician,SEC,Ball Skills,Transfer',
    comparisons: 'Patrick Surtain II,Jalen Ramsey',
    collegeStats: '{"interceptions":"2","passBreakups":"11","tackles":"45","yardsPerTarget":"3.3","penalties":"0","tdsAllowed":"0"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 12,
    projectedTeam: 'DAL',
    // Combine Day 2 — Feb 27 (DB/TE) — DID NOT PARTICIPATE
    combineGrade: 'DID_NOT_PARTICIPATE',
    combineNotes: 'Did not participate in on-field drills at the combine. Will rely on LSU pro day to showcase athleticism.',
    bullCase: 'Ideal size and skill set for NFL outside corner. SEC production validates the talent. CB1 in this class.',
    bearCase: 'Can get grabby in press — penalties could be an issue at the next level. Did not work out at combine.',
    mediationVerdict: 'Bull case wins. Size + ball skills + SEC pedigree = franchise corner.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Olaivavega',
    lastName: 'Ioane',
    position: 'IOL',
    college: 'Penn State',
    conference: 'Big Ten',
    classYear: 'Junior',
    eligibility: 'RS-Junior',
    height: '6-4',
    weight: 325,
    paiScore: 91,
    tier: 'FIRST_ROUND',
    performance: 92,
    athleticism: 89,
    intangibles: 91,
    overallRank: 13,
    positionRank: 1,
    trend: 'STEADY',
    scoutMemo: 'DJ ranked him #11 overall. Dominant interior lineman who anchors Penn State\'s run game and pass protection. Physical, smart, and reliable. Best pure IOL in the class.',
    tags: 'Interior OL,Anchor,Smart,Penn State,Reliable',
    comparisons: 'Quenton Nelson,Joel Bitonio',
    collegeStats: '{"sacksAllowed":"1","gamesStarted":"30","penaltiesPerGame":"0.3"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 13,
    projectedTeam: 'LAR',
    // Combine Day 4 — Mar 1 (OL)
    combineGrade: 'AS_EXPECTED',
    combineNotes: 'OL workouts Sunday Mar 1. Best pure IOL in the class. Expected to show elite footwork in pass-set drills.',
    bullCase: 'Plug-and-play starter at guard or center. His versatility inside makes him scheme-proof.',
    bearCase: 'IOL is not a premium draft position. Teams may prefer positional value over a guard in Round 1.',
    mediationVerdict: 'Bull case edges it. Elite IOL are rare and transform running games.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Jordyn',
    lastName: 'Tyson',
    position: 'WR',
    college: 'Arizona State',
    conference: 'Big 12',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '6-1',
    weight: 200,
    paiScore: 90,
    tier: 'FIRST_ROUND',
    performance: 91,
    athleticism: 92,
    intangibles: 88,
    overallRank: 14,
    positionRank: 3,
    trend: 'UP',
    scoutMemo: 'DJ ranked him #15. Emerging WR talent who put up elite production at Arizona State. Physical route runner with strong hands and competitive spirit.',
    tags: 'Route Runner,Physical,Competitive,Arizona State,Vertical Threat',
    comparisons: 'Terry McLaurin,DK Metcalf (lite)',
    collegeStats: '{"receptions":"74","receivingYards":"1185","receivingTDs":"11","yardsPerCatch":"16.0"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 15,
    projectedTeam: 'TB',
    // Combine Day 3 — Feb 28 — DID NOT WORK OUT
    combineGrade: 'DID_NOT_PARTICIPATE',
    combineNotes: 'Will NOT work out at combine — recovering from hamstring injury. Will showcase at Arizona State pro day instead.',
    bullCase: 'Complete receiver who can win at all three levels. Physical enough to win contested catches and fast enough to threaten deep.',
    bearCase: 'Big 12 competition level. Hamstring injury kept him from combine. Does his production translate against top-tier corners?',
    mediationVerdict: 'Bull case edges it. His physical tools and competitive nature project well.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Colton',
    lastName: 'Hood',
    position: 'CB',
    college: 'Tennessee',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '6-1',
    weight: 195,
    paiScore: 90,
    tier: 'FIRST_ROUND',
    performance: 91,
    athleticism: 91,
    intangibles: 89,
    overallRank: 15,
    positionRank: 2,
    trend: 'STEADY',
    scoutMemo: 'DJ ranked him #16. Physical corner from Tennessee with excellent ball skills. SEC-tested and proven against top competition. Lock-down ability in press coverage.',
    tags: 'Physical,Ball Skills,SEC,Tennessee,Press Corner',
    comparisons: 'Marshon Lattimore,Tre\'Davious White',
    collegeStats: '{"interceptions":"4","passBreakups":"12","tackles":"52","forcedFumbles":"1"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 17,
    projectedTeam: 'DET',
    // Combine Day 2 — Feb 27 (DB/TE)
    combineGrade: 'AS_EXPECTED',
    combineNotes: 'Solid DB workout on Day 2. SEC pedigree confirmed. Physical press corner.',
    bullCase: 'SEC corners translate at the highest rate. His physicality and ball skills are NFL-ready.',
    bearCase: 'Not the most fluid athlete — could struggle against NFL speed in off-coverage.',
    mediationVerdict: 'Bull case edges it. SEC pedigree and physical style project well.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Jermod',
    lastName: 'McCoy',
    position: 'CB',
    college: 'Tennessee',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '6-0',
    weight: 185,
    paiScore: 90,
    tier: 'FIRST_ROUND',
    performance: 91,
    athleticism: 92,
    intangibles: 87,
    overallRank: 16,
    positionRank: 3,
    trend: 'UP',
    scoutMemo: 'DJ ranked him #14. Best tape of any CB in the class per multiple evaluators. Originally Oregon State, transferred to Tennessee. 44 tackles, 9 PBU, 4 INT in 2024. MISSED 2025 WITH TORN ACL — medical evaluation critical. Explosive, twitchy, physical.',
    tags: 'Best Tape,Twitchy,SEC,Tennessee,ACL Recovery',
    comparisons: 'Sauce Gardner (lite),Trevon Diggs',
    collegeStats: '{"interceptions":"4","passBreakups":"9","tackles":"44","forcedFumbles":"1"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 18,
    projectedTeam: 'MIN',
    // Combine Day 2 — Feb 27 — DID NOT PARTICIPATE (ACL recovery)
    combineGrade: 'DID_NOT_PARTICIPATE',
    combineNotes: 'Did NOT participate — still recovering from torn ACL (missed entire 2025 season). Medical evaluation is make-or-break. If cleared, could go top 10. If concerns linger, could slip to Day 2.',
    bullCase: 'Best tape of any CB in the class. Turnover production is elite. If medicals check out, he\'s a top-10 talent.',
    bearCase: 'Tore ACL January 2025. Missed entire season. Will he be the same player? Major medical red flag.',
    mediationVerdict: 'Split. Medical evaluation will determine if this is a steal or a disaster.',
    debateWinner: 'SPLIT',
  },
  {
    firstName: 'Cashius',
    lastName: 'Howell',
    position: 'EDGE',
    college: 'Texas A&M',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'RS-Junior',
    height: '6-4',
    weight: 260,
    paiScore: 89,
    tier: 'FIRST_ROUND',
    performance: 90,
    athleticism: 91,
    intangibles: 87,
    overallRank: 17,
    positionRank: 3,
    trend: 'UP',
    scoutMemo: 'DJ ranked him #17. Rising EDGE from Texas A&M who broke out in the 2025 season. Explosive off the edge with developing hand technique.',
    tags: 'Explosive,Rising,SEC,Texas A&M,Developing',
    comparisons: 'Brian Burns,Haason Reddick',
    collegeStats: '{"sacks":"10","TFLs":"16","tackles":"48","forcedFumbles":"2","pressures":"38"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 19,
    projectedTeam: 'CAR',
    // Combine Day 1 — Feb 26 (DL/EDGE/LB)
    armLength: '30 1/4"',
    combineGrade: 'STOCK_DOWN',
    combineNotes: '30 1/4" arms — SHORTEST of any EDGE since 1999. Reigning SEC DPOY is not concerned, but scouts are. Despite historic production, arm length creates projection risk like Rueben Bain Jr.',
    bullCase: 'Explosive athlete with SEC production. Reigning SEC Defensive Player of the Year. Development arc suggests he is still ascending.',
    bearCase: 'Shortest arms for an edge rusher since 1999. One breakout season. Arm length will limit his ability to stack blocks at the NFL level.',
    mediationVerdict: 'Split. Production is undeniable but arm length is a genuine concern for NFL projection.',
    debateWinner: 'SPLIT',
  },
  {
    firstName: 'Akheem',
    lastName: 'Mesidor',
    position: 'EDGE',
    college: 'Miami',
    conference: 'ACC',
    classYear: 'Senior',
    eligibility: 'RS-Senior',
    height: '6-3',
    weight: 262,
    paiScore: 89,
    tier: 'FIRST_ROUND',
    performance: 90,
    athleticism: 90,
    intangibles: 88,
    overallRank: 18,
    positionRank: 4,
    trend: 'STEADY',
    scoutMemo: 'DJ ranked him #18. Productive pass rusher at Miami who pairs well with Bain Jr. on the opposite side. Strong, technically sound, and consistent.',
    tags: 'Consistent,Technical,Miami,Productive,Strong',
    comparisons: 'Chandler Jones,DeMarcus Lawrence',
    collegeStats: '{"sacks":"9","TFLs":"15","tackles":"52","forcedFumbles":"2","pressures":"36"}',
    combineInvite: true,
    seniorBowl: true,
    projectedRound: 1,
    projectedPick: 20,
    projectedTeam: 'DAL',
    // Combine Day 1 — Feb 26 (DL/EDGE/LB)
    combineGrade: 'AS_EXPECTED',
    combineNotes: 'Solid workout. Not a top-tier athlete but technique and motor showed well in drills. Senior Bowl momentum continues.',
    bullCase: 'Proven production and technique at a premium position. Consistent, reliable edge presence.',
    bearCase: 'Not a top-tier athlete. Ceiling may be limited to a good-not-great starter.',
    mediationVerdict: 'Balanced. Floor is a reliable starter, which has significant value in Round 1.',
    debateWinner: 'SPLIT',
  },
  {
    firstName: 'Kenyon',
    lastName: 'Sadiq',
    position: 'TE',
    college: 'Oregon',
    conference: 'Big Ten',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '6-3',
    weight: 245,
    paiScore: 91,
    tier: 'FIRST_ROUND',
    performance: 92,
    athleticism: 91,
    intangibles: 90,
    overallRank: 19,
    positionRank: 1,
    trend: 'UP',
    scoutMemo: 'Kiper\'s #1 TE. Unanimous #1 TE on ESPN positional rankings (all 5 analysts). 80 career receptions, 892 yards, 11 TDs over 3 seasons. Projected 4.55 forty. Rare explosiveness at TE. Route-running refinement needed.',
    tags: 'Complete TE,Explosive,Kiper #1 TE,Oregon,Unanimous #1',
    comparisons: 'Vernon Davis,Kyle Pitts',
    collegeStats: '{"receptions":"80","receivingYards":"892","receivingTDs":"11","yardsPerCatch":"11.2","projectedForty":"4.55"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 21,
    projectedTeam: 'PIT',
    // Combine Day 2 — Feb 27 (DB/TE) — COMBINE RECORD BREAKER
    fortyYard: 4.39,
    verticalJump: 38.5,
    broadJump: 128,
    combineGrade: 'STOCK_UP',
    combineNotes: 'BROKE Vernon Davis\' combine TE record with 4.39 40-yard dash (corrected from initial 4.40). Historic speed for the position. Cemented himself as TE1 and a legit first-round pick.',
    bullCase: 'Best TE in the class by a wide margin. Broke the all-time TE combine 40 record. Can be a mismatch weapon from Day 1. Unanimous #1 ranking is rare.',
    bearCase: 'TE is a slow-developing NFL position. May take 2-3 years to reach full potential.',
    mediationVerdict: 'Bull case wins. Record-breaking speed + unanimous top ranking = first-round lock.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Denzel',
    lastName: 'Boston',
    position: 'WR',
    college: 'Washington',
    conference: 'Big Ten',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '6-3',
    weight: 205,
    paiScore: 89,
    tier: 'FIRST_ROUND',
    performance: 90,
    athleticism: 90,
    intangibles: 88,
    overallRank: 20,
    positionRank: 4,
    trend: 'STEADY',
    scoutMemo: 'DJ ranked him #20. Big-bodied receiver from Washington with excellent contested catch ability. Physical X-receiver who dominates at the catch point.',
    tags: 'X-Receiver,Contested Catch,Physical,Washington,Catch Point',
    comparisons: 'Mike Evans,Brandon Marshall',
    collegeStats: '{"receptions":"68","receivingYards":"1052","receivingTDs":"9","yardsPerCatch":"15.5"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 22,
    projectedTeam: 'LAC',
    // Combine Day 3 — Feb 28 (QB/RB/WR)
    combineGrade: 'AS_EXPECTED',
    combineNotes: 'WR workouts today Feb 28. Big-bodied X-receiver expected to show well in contested catch drills and route work.',
    bullCase: 'True X-receiver with the size and hands to dominate in the red zone. Physical presence that defenses must respect.',
    bearCase: 'Not a great separator — relies heavily on physicality. May struggle against elite NFL press corners.',
    mediationVerdict: 'Bull case edges it. Contested catch ability is a bankable NFL skill.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Ty',
    lastName: 'Simpson',
    position: 'QB',
    college: 'Alabama',
    conference: 'SEC',
    classYear: 'Senior',
    eligibility: 'RS-Senior',
    height: '6-2',
    weight: 208,
    paiScore: 88,
    tier: 'FIRST_ROUND',
    performance: 88,
    athleticism: 91,
    intangibles: 86,
    overallRank: 21,
    positionRank: 2,
    trend: 'UP',
    scoutMemo: 'Former 5-star recruit. 15 career starts. 305/473 (64.5%), 3,567 yards, 28 TD, 5 INT in 2025. Second-Team All-SEC. Led Alabama to CFP quarterfinals. Only other first-round QB besides Mendoza. CBS mocked him to Pittsburgh at #21.',
    tags: 'Mobile,5-Star,Alabama,Developing,Upside',
    comparisons: 'Josh Allen (early),Jalen Hurts',
    collegeStats: '{"completionPct":"64.5%","passingYards":"3567","passingTDs":"28","interceptions":"5","rushingYards":"542","rushingTDs":"7","careerStarts":"15"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 21,
    projectedTeam: 'PIT',
    // Combine Day 3 — Feb 28 (QB/RB/WR) — WILL THROW
    combineGrade: 'AS_EXPECTED',
    combineNotes: 'Chose to throw at combine (unlike Mendoza). Key opportunity to solidify first-round status. "I\'m a franchise quarterback" — said in combine presser. Fight for QB2 is on.',
    bullCase: 'Dual-threat QB with an NFL arm. Alabama pedigree and SEC experience. Throwing at combine shows confidence. High ceiling if passing game clicks.',
    bearCase: 'Still developing as a passer. Accuracy is inconsistent. Not a finished product like Mendoza.',
    mediationVerdict: 'Balanced. High upside but requires the right coaching staff and patience.',
    debateWinner: 'SPLIT',
  },

  // ─── DAY 2 ─────────────────────────────────────────────────
  {
    firstName: 'KC',
    lastName: 'Concepcion',
    position: 'WR',
    college: 'Texas A&M',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '6-2',
    weight: 200,
    paiScore: 87,
    tier: 'DAY_2',
    performance: 88,
    athleticism: 88,
    intangibles: 86,
    overallRank: 22,
    positionRank: 5,
    trend: 'STEADY',
    scoutMemo: 'Physical receiver from Texas A&M with excellent hands and route-running. SEC production validates his talent.',
    tags: 'Physical,Hands,SEC,Route Runner,Consistent',
    comparisons: 'Michael Thomas,Allen Robinson',
    collegeStats: '{"receptions":"70","receivingYards":"1018","receivingTDs":"8","yardsPerCatch":"14.5"}',
    combineInvite: true,
    seniorBowl: true,
    projectedRound: 2,
    projectedPick: 36,
    bullCase: 'Reliable possession receiver who can be a WR2 from Day 1.',
    bearCase: 'Lacks elite speed. May be limited to a possession role.',
    mediationVerdict: 'Bull case edges it. Reliable receivers have long NFL careers.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Kayden',
    lastName: 'McDonald',
    position: 'DT',
    college: 'Ohio State',
    conference: 'Big Ten',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '6-3',
    weight: 310,
    paiScore: 87,
    tier: 'DAY_2',
    performance: 88,
    athleticism: 87,
    intangibles: 86,
    overallRank: 23,
    positionRank: 1,
    trend: 'STEADY',
    scoutMemo: 'Stout interior defender from Ohio State. Anchors against the run and generates interior pressure. Part of the Ohio State defensive factory.',
    tags: 'Interior,Anchor,Ohio State,Run Stuffer,Consistent',
    comparisons: 'Javon Hargrave,Sheldon Rankins',
    collegeStats: '{"sacks":"5","TFLs":"12","tackles":"48","pressures":"28"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 2,
    projectedPick: 38,
    bullCase: 'Proven interior defender from elite program. Day 1 run defender.',
    bearCase: 'Not a dynamic pass rusher. Limited to early-down role.',
    mediationVerdict: 'Balanced. Solid starter or excellent rotational piece.',
    debateWinner: 'SPLIT',
  },
  {
    firstName: 'Peter',
    lastName: 'Woods',
    position: 'DT',
    college: 'Clemson',
    conference: 'ACC',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '6-3',
    weight: 315,
    paiScore: 87,
    tier: 'DAY_2',
    performance: 88,
    athleticism: 88,
    intangibles: 85,
    overallRank: 24,
    positionRank: 2,
    trend: 'STEADY',
    scoutMemo: 'Kiper\'s #1 DT. Former 5-star recruit (#9 overall). Career 99 tackles, 14.5 TFL, 5.0 sacks. Bench 490, squat 700, 4.86 forty. #5 on Bruce Feldman\'s Freaks List. Consensus top interior defender.',
    tags: 'Freaks List,Power,5-Star,Clemson,Explosive',
    comparisons: 'Grady Jarrett,Christian Wilkins',
    collegeStats: '{"sacks":"5.0","TFLs":"14.5","tackles":"99","pressures":"32","bench":"490","squat":"700"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 2,
    projectedPick: 40,
    bullCase: 'Explosive interior pass rusher. Can disrupt from the 3-tech alignment.',
    bearCase: 'Undersized for an every-down role. May be a pass-rush specialist.',
    mediationVerdict: 'Bull case edges it. Interior pressure is highly valued.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'R Mason',
    lastName: 'Thomas',
    position: 'EDGE',
    college: 'Oklahoma',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '6-4',
    weight: 248,
    paiScore: 86,
    tier: 'DAY_2',
    performance: 87,
    athleticism: 88,
    intangibles: 84,
    overallRank: 25,
    positionRank: 5,
    trend: 'UP',
    scoutMemo: 'Athletic edge rusher from Oklahoma. Long and rangy with developing technique. High-ceiling prospect.',
    tags: 'Athletic,Length,Oklahoma,High Ceiling,Developing',
    comparisons: 'Josh Sweat,Nolan Smith',
    collegeStats: '{"sacks":"8","TFLs":"14","tackles":"44","forcedFumbles":"2","pressures":"34"}',
    combineInvite: true,
    seniorBowl: true,
    projectedRound: 2,
    projectedPick: 42,
    bullCase: 'Length and athleticism project well. Ceiling is a starting NFL edge.',
    bearCase: 'Still learning to use his length. Raw technique.',
    mediationVerdict: 'Bull case edges it. The physical tools are there.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Christen',
    lastName: 'Miller',
    position: 'DT',
    college: 'Georgia',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '6-3',
    weight: 305,
    paiScore: 86,
    tier: 'DAY_2',
    performance: 87,
    athleticism: 86,
    intangibles: 86,
    overallRank: 26,
    positionRank: 3,
    trend: 'STEADY',
    scoutMemo: 'Georgia DL factory product. Dominant run defender with growing pass-rush ability. SEC-tested and consistent.',
    tags: 'Georgia DL,Run Defender,SEC,Consistent,Physical',
    comparisons: 'DeForest Buckner (lite),Akiem Hicks',
    collegeStats: '{"sacks":"4","TFLs":"11","tackles":"46","pressures":"24"}',
    combineInvite: true,
    seniorBowl: true,
    projectedRound: 2,
    projectedPick: 45,
    bullCase: 'Georgia DL pipeline is proven. Physical, consistent run defender.',
    bearCase: 'Not a dynamic pass rusher. Limited ceiling as a rotational piece.',
    mediationVerdict: 'Balanced. Reliable DT with good floor.',
    debateWinner: 'SPLIT',
  },
  {
    firstName: 'T.J.',
    lastName: 'Parker',
    position: 'EDGE',
    college: 'Clemson',
    conference: 'ACC',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '6-5',
    weight: 260,
    paiScore: 86,
    tier: 'DAY_2',
    performance: 87,
    athleticism: 87,
    intangibles: 84,
    overallRank: 27,
    positionRank: 6,
    trend: 'STEADY',
    scoutMemo: 'Big, physical edge rusher from Clemson. Wins with power and length at the point of attack. High-floor prospect.',
    tags: 'Power,Length,Clemson,Physical,High Floor',
    comparisons: 'Trey Hendrickson,Montez Sweat',
    collegeStats: '{"sacks":"8","TFLs":"13","tackles":"46","forcedFumbles":"2","pressures":"30"}',
    combineInvite: true,
    seniorBowl: true,
    projectedRound: 1,
    projectedPick: 30,
    projectedTeam: 'DEN',
    // Combine Day 1 — Feb 26 — STOCK UP
    fortyYard: 4.68,
    verticalJump: 34.0,
    combineGrade: 'STOCK_UP',
    combineNotes: 'Built on impressive Senior Bowl week with solid combine. 4.68 40 and 34" vertical at 6-4, 263 lbs. Ascension back into late Round 1 picture after disappointing final Clemson season.',
    bullCase: 'Size and power make him an immediate contributor against the run. Senior Bowl + combine are erasing concerns from 2025 season.',
    bearCase: 'Disappointing final college season. Senior Bowl/combine may be masking actual game tape issues.',
    mediationVerdict: 'Bull case edges it. Two strong pre-draft showings > one bad season.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Antonio',
    lastName: 'Williams',
    position: 'WR',
    college: 'Clemson',
    conference: 'ACC',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '6-0',
    weight: 188,
    paiScore: 86,
    tier: 'DAY_2',
    performance: 87,
    athleticism: 88,
    intangibles: 84,
    overallRank: 28,
    positionRank: 6,
    trend: 'UP',
    scoutMemo: 'Quick, shifty receiver from Clemson. Excellent route runner with strong hands. One of 11 WRs on DJ\'s initial top 50.',
    tags: 'Quick,Shifty,Route Runner,Clemson,Hands',
    comparisons: 'Adam Thielen,Stefon Diggs',
    collegeStats: '{"receptions":"72","receivingYards":"988","receivingTDs":"8","yardsPerCatch":"13.7"}',
    combineInvite: true,
    seniorBowl: true,
    projectedRound: 2,
    projectedPick: 50,
    bullCase: 'Reliable route runner who gets open consistently. High-floor WR3.',
    bearCase: 'Lacks elite size and speed. May not be a true #1 WR.',
    mediationVerdict: 'Bull case edges it. Reliable WR production translates.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Monroe',
    lastName: 'Freeling',
    position: 'OT',
    college: 'Georgia',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'RS-Junior',
    height: '6-7',
    weight: 312,
    paiScore: 86,
    tier: 'DAY_2',
    performance: 87,
    athleticism: 86,
    intangibles: 85,
    overallRank: 29,
    positionRank: 3,
    trend: 'STEADY',
    scoutMemo: 'ESPN consensus top-4 OT. Massive frame from Georgia with excellent length and anchor. Developing technique to match his physical tools.',
    tags: 'Size,Length,Georgia,Anchor,Developing',
    comparisons: 'Orlando Brown Jr.,D.J. Humphries',
    collegeStats: '{"sacksAllowed":"2","gamesStarted":"24","penaltiesPerGame":"0.5"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 2,
    projectedPick: 52,
    bullCase: 'Ideal size and length for an NFL left tackle. Physical tools are rare.',
    bearCase: 'Technique is still raw. May take 1-2 years to develop into a starter.',
    mediationVerdict: 'Bull case edges it. The frame and athleticism are worth the wait.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Emmanuel',
    lastName: 'McNeil-Warren',
    position: 'S',
    college: 'Toledo',
    conference: 'MAC',
    classYear: 'Senior',
    eligibility: 'RS-Senior',
    height: '6-2',
    weight: 210,
    paiScore: 85,
    tier: 'DAY_2',
    performance: 86,
    athleticism: 87,
    intangibles: 83,
    overallRank: 30,
    positionRank: 2,
    trend: 'UP',
    scoutMemo: 'DJ ranked him #19. Small-school safety who has risen up boards with elite combine projections. Range and ball skills are NFL-caliber.',
    tags: 'Range,Ball Skills,Small School,Rising,Combine Riser',
    comparisons: 'Budda Baker,Jessie Bates III',
    collegeStats: '{"interceptions":"5","passBreakups":"10","tackles":"78","forcedFumbles":"2"}',
    combineInvite: true,
    seniorBowl: true,
    projectedRound: 2,
    projectedPick: 55,
    combineGrade: 'AS_EXPECTED',
    combineNotes: 'Day 2 DB workout. Expected to confirm elite range with strong 40 time and vertical.',
    bullCase: 'Elite range and instincts from the back end. Small-school players often outperform their draft slot.',
    bearCase: 'MAC competition level. Can his production translate against NFL speed?',
    mediationVerdict: 'Bull case edges it. The physical tools and production are real.',
    debateWinner: 'BULL',
  },

  // ─── COMBINE STANDOUTS (added Feb 28, 2026) ──────────────────
  // Players who made major noise at the 2026 NFL Combine
  {
    firstName: 'Lorenzo',
    lastName: 'Styles Jr.',
    position: 'S',
    college: 'Ohio State',
    conference: 'Big Ten',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '6-1',
    weight: 198,
    paiScore: 89,
    tier: 'FIRST_ROUND',
    performance: 88,
    athleticism: 99,
    intangibles: 87,
    overallRank: 22,
    positionRank: 2,
    trend: 'UP',
    scoutMemo: 'Brother of LB Sonny Styles. The Styles brothers both lit up the combine. Lorenzo ran the fastest 40 by a safety since at least 2003.',
    tags: 'Elite Speed,Ohio State,Styles Family,Range,Combine Star',
    comparisons: 'Tyrann Mathieu,Antoine Winfield Jr.',
    collegeStats: '{"interceptions":"3","passBreakups":"8","tackles":"55","forcedFumbles":"1"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 1,
    projectedPick: 23,
    projectedTeam: 'PHI',
    // Combine Day 2 — Feb 27 — FASTEST 40 AT THE COMBINE
    fortyYard: 4.27,
    combineGrade: 'STOCK_UP',
    combineNotes: 'RAN 4.27 — FASTEST 40-YARD DASH AT THE ENTIRE 2026 COMBINE. Fastest safety 40 since at least 2003. The Styles brothers are the story of the combine.',
    bullCase: 'Historic combine speed. Ohio State pedigree. Brother of top-10 LB Sonny Styles — football family DNA. Game-changing range from the safety position.',
    bearCase: 'Speed alone doesn\'t make a safety. Needs to prove he can tackle in the box and play in traffic.',
    mediationVerdict: 'Bull case wins. Historic speed + OSU production = first-round safety.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Eli',
    lastName: 'Stowers',
    position: 'TE',
    college: 'Vanderbilt',
    conference: 'SEC',
    classYear: 'Senior',
    eligibility: 'RS-Senior',
    height: '6-4',
    weight: 248,
    paiScore: 86,
    tier: 'DAY_2',
    performance: 85,
    athleticism: 96,
    intangibles: 82,
    overallRank: 35,
    positionRank: 2,
    trend: 'UP',
    scoutMemo: 'Converted QB turned TE from Vanderbilt. Raw but incredibly athletic. Combine performance was historic.',
    tags: 'Athletic Freak,Converted QB,Vanderbilt,SEC,Combine Star',
    comparisons: 'Darren Waller,Jimmy Graham',
    collegeStats: '{"receptions":"38","receivingYards":"485","receivingTDs":"6","yardsPerCatch":"12.8"}',
    combineInvite: true,
    seniorBowl: true,
    projectedRound: 2,
    projectedPick: 40,
    // Combine Day 2 — Feb 27 — DOUBLE TE RECORD BREAKER
    verticalJump: 45.5,
    broadJump: 135,
    combineGrade: 'STOCK_UP',
    combineNotes: 'BROKE BOTH combine TE records — 45.5" vertical (record) and 11\'3" broad jump (record). Most explosive TE testing ever recorded at the combine. Could push into late Round 1.',
    bullCase: 'Most athletic TE prospect ever measured at the combine. Two all-time records. Converted QB who understands route concepts. Sky-high ceiling.',
    bearCase: 'Vanderbilt production was modest. Still learning the position. Raw route tree.',
    mediationVerdict: 'Bull case wins. You can\'t teach that athleticism. Records are records.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Caleb',
    lastName: 'Banks',
    position: 'DT',
    college: 'Florida',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '6-6 1/4',
    weight: 327,
    paiScore: 87,
    tier: 'DAY_2',
    performance: 86,
    athleticism: 92,
    intangibles: 85,
    overallRank: 32,
    positionRank: 3,
    trend: 'UP',
    scoutMemo: 'Massive DT with historic wingspan. 85 3/4" wingspan is the longest among combine DTs since 1999. 98th percentile height, 89th percentile weight, 94th percentile hand size.',
    tags: 'Wingspan Record,Massive,Florida,SEC,Physical Freak',
    comparisons: 'Vita Vea,Derrick Brown',
    collegeStats: '{"sacks":"3.5","TFLs":"8","tackles":"42","pressures":"22"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 2,
    projectedPick: 38,
    // Combine Day 1 — Feb 26 — HISTORIC MEASUREMENTS
    fortyYard: 5.04,
    armLength: '35"',
    handSize: '10 7/8"',
    combineGrade: 'STOCK_UP',
    combineNotes: '85 3/4" wingspan — LONGEST among combine DTs since 1999. 94th percentile arm length (35"), 94th percentile hand size (10 7/8"). At 6-6 1/4, 327 lbs, he\'s a physical anomaly. Early-round DT upside.',
    bullCase: 'Historic length and size create mismatches NFL OLs have never seen. SEC production backing the measurements.',
    bearCase: 'On-field drills ended early. Still raw. 5.04 40 is slow even for a DT.',
    mediationVerdict: 'Bull case edges it. Length matters at DT and his is literally record-setting.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Gracen',
    lastName: 'Halton',
    position: 'DT',
    college: 'Oklahoma',
    conference: 'Big 12',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '6-3',
    weight: 293,
    paiScore: 86,
    tier: 'DAY_2',
    performance: 86,
    athleticism: 93,
    intangibles: 83,
    overallRank: 36,
    positionRank: 4,
    trend: 'UP',
    scoutMemo: 'Oklahoma 3-technique who exploded at the combine. 36.5" vertical is 3rd highest for a DT in the last 20 years.',
    tags: 'Explosive,3-Technique,Oklahoma,Combine Riser,Vertical Record',
    comparisons: 'Javon Hargrave,Grady Jarrett',
    collegeStats: '{"sacks":"4.5","TFLs":"10","tackles":"40","pressures":"26"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 2,
    projectedPick: 42,
    // Combine Day 1 — Feb 26
    fortyYard: 4.83,
    verticalJump: 36.5,
    combineGrade: 'STOCK_UP',
    combineNotes: '36.5" vertical jump — 3rd highest for a DT in the last 20 years. Also ran 4.83 40 at 293 lbs. One of the most impressive DT combine performances. Could push into top 100.',
    bullCase: 'Elite explosiveness for a DT. 3rd best vertical ever at the position. Quick-twitch interior disruptor.',
    bearCase: 'Undersized at 293 lbs. Can he hold up against NFL double teams?',
    mediationVerdict: 'Bull case wins. Explosiveness at DT is rare and valuable.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Malachi',
    lastName: 'Lawrence',
    position: 'EDGE',
    college: 'Georgia',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '6-3',
    weight: 248,
    paiScore: 85,
    tier: 'DAY_2',
    performance: 84,
    athleticism: 93,
    intangibles: 82,
    overallRank: 37,
    positionRank: 7,
    trend: 'UP',
    scoutMemo: 'No one helped themselves more at the combine than Lawrence. His whole workout screamed NFL burst.',
    tags: 'Burst,Combine Riser,Georgia,SEC,Quick-Twitch',
    comparisons: 'Matthew Judon,Josh Sweat',
    collegeStats: '{"sacks":"6","TFLs":"9","tackles":"38","pressures":"28"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 2,
    projectedPick: 45,
    // Combine Day 1 — Feb 26 — BIGGEST RISER
    fortyYard: 4.52,
    tenYardSplit: 1.59,
    verticalJump: 40.0,
    broadJump: 130,
    combineGrade: 'STOCK_UP',
    combineNotes: 'BIGGEST RISER of the combine. 4.52 40 with 1.59 10-yard split, 40" vertical, 10\'10" broad jump. His whole workout screamed NFL burst. Forced himself into the top cluster of the Day 2 edge board.',
    bullCase: 'Combine performance forced himself into first-round conversation. Elite burst and explosiveness. Georgia pedigree.',
    bearCase: 'College production doesn\'t match the athleticism. Why didn\'t the traits show up more in games?',
    mediationVerdict: 'Bull case edges it. The physical tools are undeniable.',
    debateWinner: 'BULL',
  },
  {
    firstName: 'Toriano',
    lastName: 'Pride Jr.',
    position: 'CB',
    college: 'Missouri',
    conference: 'SEC',
    classYear: 'Senior',
    eligibility: 'RS-Senior',
    height: '5-11',
    weight: 183,
    paiScore: 84,
    tier: 'DAY_2',
    performance: 83,
    athleticism: 94,
    intangibles: 80,
    overallRank: 38,
    positionRank: 4,
    trend: 'UP',
    scoutMemo: 'Fastest CB at the 2026 combine. Improved from 4.36 first run to 4.32 on second attempt.',
    tags: 'Speed,Missouri,SEC,Combine Riser,Slot Corner',
    comparisons: 'Trevon Diggs (early),Asante Samuel Jr.',
    collegeStats: '{"interceptions":"3","passBreakups":"9","tackles":"48","forcedFumbles":"1"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 3,
    projectedPick: 65,
    // Combine Day 2 — Feb 27
    fortyYard: 4.32,
    combineGrade: 'STOCK_UP',
    combineNotes: 'Fastest CB 40 at 4.32 (improved from 4.36 on first run). Elite speed that translates to NFL coverage.',
    bullCase: 'Fastest CB in the class. Speed kills in the NFL. Missouri/SEC pedigree.',
    bearCase: 'Undersized. Speed doesn\'t compensate for technique gaps in press coverage.',
    mediationVerdict: 'Bull case edges it. Speed is the one thing you can\'t teach.',
    debateWinner: 'BULL',
  },
  {
    firstName: "D'Angelo",
    lastName: 'Ponds',
    position: 'CB',
    college: 'Indiana',
    conference: 'Big Ten',
    classYear: 'Senior',
    eligibility: 'RS-Senior',
    height: '5-8 5/8',
    weight: 180,
    paiScore: 83,
    tier: 'DAY_2',
    performance: 83,
    athleticism: 95,
    intangibles: 78,
    overallRank: 42,
    positionRank: 5,
    trend: 'UP',
    scoutMemo: 'Small but explosive. Entered combine with concerns about size. Answered with 4th-best CB vertical in combine history.',
    tags: 'Explosive,Small But Mighty,Indiana,Big Ten,Vertical Record',
    comparisons: 'Darius Slay (at his size),Bene Benwikere',
    collegeStats: '{"interceptions":"4","passBreakups":"12","tackles":"52","forcedFumbles":"1"}',
    combineInvite: true,
    seniorBowl: true,
    projectedRound: 3,
    projectedPick: 72,
    // Combine Day 2 — Feb 27
    verticalJump: 43.5,
    combineGrade: 'STOCK_UP',
    combineNotes: '43.5" vertical — 4th BEST in combine CB history despite being 5-8 5/8. Silenced size concerns with historic leaping ability. Could jump into Day 2 conversation.',
    bullCase: 'Historic vertical erases size concerns. If he can high-point the ball, he can compete at any height. Championship-winning Indiana program.',
    bearCase: 'At 5-8 5/8, there\'s a hard floor for how much a vertical jump compensates for lack of length. NFL WRs are big.',
    mediationVerdict: 'Split. Athleticism is elite but size is a real limitation at the NFL level.',
    debateWinner: 'SPLIT',
  },
  {
    firstName: 'Garrett',
    lastName: 'Nussmeier',
    position: 'QB',
    college: 'LSU',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '6-2',
    weight: 218,
    paiScore: 84,
    tier: 'DAY_2',
    performance: 85,
    athleticism: 83,
    intangibles: 84,
    overallRank: 40,
    positionRank: 3,
    trend: 'STEADY',
    scoutMemo: 'LSU QB expected to throw at combine alongside Ty Simpson. Competing for QB2 in the class. Strong arm, SEC experience.',
    tags: 'Strong Arm,LSU,SEC,Competing,Day 2 QB',
    comparisons: 'Baker Mayfield,Derek Carr',
    collegeStats: '{"completionPct":"63.2%","passingYards":"3200","passingTDs":"24","interceptions":"8"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 2,
    projectedPick: 48,
    // Combine Day 3 — Feb 28 — WILL THROW
    combineGrade: 'AS_EXPECTED',
    combineNotes: 'Expected to throw at combine today. Competing with Ty Simpson for QB2 status. LSU pro day could be more impactful.',
    bullCase: 'Strong arm and SEC pedigree. Could be this year\'s late-riser QB.',
    bearCase: 'Not elite at anything. Decent across the board but lacks a standout trait.',
    mediationVerdict: 'Balanced. Solid QB2 candidate but needs the right system.',
    debateWinner: 'SPLIT',
  },
  {
    firstName: 'Carson',
    lastName: 'Beck',
    position: 'QB',
    college: 'Miami',
    conference: 'ACC',
    classYear: 'Senior',
    eligibility: 'RS-Senior',
    height: '6-4',
    weight: 225,
    paiScore: 82,
    tier: 'DAY_2',
    performance: 82,
    athleticism: 81,
    intangibles: 83,
    overallRank: 45,
    positionRank: 4,
    trend: 'DOWN',
    scoutMemo: 'Transferred from Georgia to Miami after 2024. Former top QB prospect whose stock has fallen. Still has arm talent but decision-making has regressed.',
    tags: 'Arm Talent,Georgia Transfer,Miami,Falling,Pocket Passer',
    comparisons: 'Sam Darnold,Dwayne Haskins',
    collegeStats: '{"completionPct":"61.5%","passingYards":"2950","passingTDs":"20","interceptions":"12"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 2,
    projectedPick: 55,
    // Combine Day 3 — Feb 28 — WILL THROW
    combineGrade: 'AS_EXPECTED',
    combineNotes: 'Expected to throw at combine. Needs a strong showing to stop stock slide. Once a projected top-10 pick, now a Day 2 QB.',
    bullCase: 'Pure arm talent is still first-round caliber. A strong combine showing could restart the hype. Still young.',
    bearCase: 'Regression from Georgia to Miami is concerning. Turnovers are a pattern, not an aberration.',
    mediationVerdict: 'Bear case leads. Too many red flags to overcome with a single combine workout.',
    debateWinner: 'BEAR',
  },
  {
    firstName: 'Drew',
    lastName: 'Allar',
    position: 'QB',
    college: 'Penn State',
    conference: 'Big Ten',
    classYear: 'Senior',
    eligibility: 'RS-Senior',
    height: '6-5',
    weight: 238,
    paiScore: 81,
    tier: 'DAY_2',
    performance: 80,
    athleticism: 82,
    intangibles: 81,
    overallRank: 48,
    positionRank: 5,
    trend: 'STEADY',
    scoutMemo: 'Big, physical QB from Penn State. "Everything happens for a reason" — said at combine reflecting on PSU career. Size/arm combo is intriguing for NFL.',
    tags: 'Big Arm,Penn State,Big Ten,Physical,Project',
    comparisons: 'Paxton Lynch,Josh Allen (physical)',
    collegeStats: '{"completionPct":"62.8%","passingYards":"2800","passingTDs":"18","interceptions":"9"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 3,
    projectedPick: 70,
    // Combine Day 3 — Feb 28 — WILL THROW
    combineGrade: 'AS_EXPECTED',
    combineNotes: 'Expected to throw at combine. At 6-5, 238 lbs, has ideal NFL size. Pro day at Penn State will also be important.',
    bullCase: 'Ideal NFL size and arm strength. Raw tools are first-round caliber. Could be a developmental franchise QB.',
    bearCase: 'Accuracy and touch are inconsistent. May be a career backup.',
    mediationVerdict: 'Balanced. Upside is there but so is the bust risk.',
    debateWinner: 'SPLIT',
  },
  {
    firstName: 'Zachariah',
    lastName: 'Branch',
    position: 'WR',
    college: 'USC',
    conference: 'Big Ten',
    classYear: 'Junior',
    eligibility: 'Junior',
    height: '5-9',
    weight: 175,
    paiScore: 83,
    tier: 'DAY_2',
    performance: 82,
    athleticism: 96,
    intangibles: 78,
    overallRank: 43,
    positionRank: 5,
    trend: 'UP',
    scoutMemo: 'Former USC and Georgia WR/return specialist. Expected to put on a show in the 40-yard dash with electric speed. Unique style of play.',
    tags: 'Speed Demon,Return Specialist,USC,Georgia,Electric',
    comparisons: 'Tyreek Hill (ceiling),Deonte Harty',
    collegeStats: '{"receptions":"45","receivingYards":"650","receivingTDs":"5","kickReturnTDs":"3","puntReturnTDs":"2"}',
    combineInvite: true,
    seniorBowl: false,
    projectedRound: 2,
    projectedPick: 50,
    // Combine Day 3 — Feb 28
    combineGrade: 'AS_EXPECTED',
    combineNotes: 'Expected to blaze the 40. Return czar who could be the fastest player at the entire combine. WR/RB/KR workout today.',
    bullCase: 'Game-breaking speed that changes how defenses have to play. Return ability provides immediate Day 1 value.',
    bearCase: 'Undersized. Limited route tree. May be a gadget player at the next level.',
    mediationVerdict: 'Balanced. Speed is elite but NFL viability depends on route development.',
    debateWinner: 'SPLIT',
  },
];

// ─────────────────────────────────────────────────────────────
// 2025 Redraft — rookie season re-evaluation
// Players from the 2025 NFL Draft who just completed their rookie season
// ─────────────────────────────────────────────────────────────

export interface RedraftProspect extends SeedDraftProspect {
  nflTeam: string;
  draftPick: string;
  rookieStats?: string;
  rookieGrade: number;
  rookieAssessment?: string;
  injuryNote?: string;
}

export const REDRAFT_2025_CLASS: RedraftProspect[] = [
  {
    firstName: 'Shedeur',
    lastName: 'Sanders',
    position: 'QB',
    college: 'Colorado',
    conference: 'Big 12',
    classYear: 'Senior',
    height: '6-2',
    weight: 215,
    paiScore: 88,
    tier: 'TOP_5',
    performance: 86,
    athleticism: 90,
    intangibles: 90,
    overallRank: 1,
    positionRank: 1,
    trend: 'STEADY',
    nflTeam: 'Tennessee Titans',
    draftPick: '1.01',
    rookieStats: '{"completionPct":"65.4%","passingYards":"3412","passingTDs":"22","interceptions":"11","qbr":"74.2","wins":"5"}',
    rookieGrade: 72,
    rookieAssessment: 'Showed the accuracy and poise that made him QB1. Titans\' roster around him is thin. Improving as the season went on — Year 2 should be a leap.',
    scoutMemo: 'Went #1 overall to Tennessee. Flashed pro-ready accuracy but struggled behind a weak OL.',
    comparisons: 'Russell Wilson (trajectory)',
  },
  {
    firstName: 'Travis',
    lastName: 'Hunter',
    position: 'CB/WR',
    college: 'Colorado',
    conference: 'Big 12',
    classYear: 'Junior',
    height: '6-1',
    weight: 185,
    paiScore: 95,
    tier: 'TOP_5',
    performance: 93,
    athleticism: 97,
    intangibles: 95,
    overallRank: 2,
    positionRank: 1,
    trend: 'UP',
    nflTeam: 'Cleveland Browns',
    draftPick: '1.02',
    rookieStats: '{"interceptions":"4","passBreakups":"14","tackles":"58","receptions":"24","receivingYards":"312","receivingTDs":"3"}',
    rookieGrade: 91,
    rookieAssessment: 'Lived up to the hype. Played CB primarily but was deployed on offense in key situations. Generational talent is translating. DROY candidate.',
    scoutMemo: 'Heisman winner taken #2. Cleveland is using him primarily at CB with offensive snaps mixed in. Already a top-10 corner.',
    comparisons: 'Deion Sanders (ceiling)',
  },
  {
    firstName: 'Cam',
    lastName: 'Ward',
    position: 'QB',
    college: 'Miami',
    conference: 'ACC',
    classYear: 'Senior',
    height: '6-2',
    weight: 220,
    paiScore: 86,
    tier: 'TOP_5',
    performance: 84,
    athleticism: 93,
    intangibles: 82,
    overallRank: 3,
    positionRank: 2,
    trend: 'STEADY',
    nflTeam: 'New York Giants',
    draftPick: '1.03',
    rookieStats: '{"completionPct":"61.8%","passingYards":"3188","passingTDs":"19","interceptions":"14","qbr":"68.1","wins":"4"}',
    rookieGrade: 64,
    rookieAssessment: 'The gunslinger tendencies showed up in the NFL. Too many turnovers in a difficult situation. The arm talent is real but the decision-making needs work.',
    scoutMemo: 'Taken #3 by NYG. Hero-ball tendencies are more pronounced against NFL defenses. Giants at #5 in 2026 is partly on him.',
    comparisons: 'Sam Darnold (situation)',
    injuryNote: 'Missed 2 games with shoulder contusion',
  },
  {
    firstName: 'Abdul',
    lastName: 'Carter',
    position: 'EDGE',
    college: 'Penn State',
    conference: 'Big Ten',
    classYear: 'Junior',
    height: '6-3',
    weight: 252,
    paiScore: 93,
    tier: 'TOP_5',
    performance: 92,
    athleticism: 96,
    intangibles: 91,
    overallRank: 4,
    positionRank: 1,
    trend: 'UP',
    nflTeam: 'New England Patriots',
    draftPick: '1.04',
    rookieStats: '{"sacks":"9.5","TFLs":"16","tackles":"52","forcedFumbles":"3","pressures":"48","pffGrade":"82.4"}',
    rookieGrade: 87,
    rookieAssessment: 'Immediate impact as a pass rusher. The Parsons comp is holding up. Patriots defense improved significantly with him on the edge. Made the Super Bowl.',
    scoutMemo: 'Penn State EDGE taken #4. Dominant rookie pass-rush season. Anchored the Patriots defense that reached Super Bowl LX.',
    comparisons: 'Micah Parsons (confirmed)',
  },
  {
    firstName: 'Tetairoa',
    lastName: 'McMillan',
    position: 'WR',
    college: 'Arizona',
    conference: 'Big 12',
    classYear: 'Junior',
    height: '6-5',
    weight: 212,
    paiScore: 88,
    tier: 'TOP_5',
    performance: 86,
    athleticism: 90,
    intangibles: 88,
    overallRank: 5,
    positionRank: 1,
    trend: 'STEADY',
    nflTeam: 'Jacksonville Jaguars',
    draftPick: '1.05',
    rookieStats: '{"receptions":"62","receivingYards":"934","receivingTDs":"7","yardsPerCatch":"15.1"}',
    rookieGrade: 76,
    rookieAssessment: 'Solid rookie year. Showed the contested catch ability that made him a top pick. Chemistry with Trevor Lawrence growing. The size advantage is real.',
    scoutMemo: 'Arizona WR taken #5 by Jacksonville. Steady production as a rookie. Should ascend in Year 2.',
    comparisons: 'Mike Evans (trajectory)',
  },
  {
    firstName: 'Ashton',
    lastName: 'Jeanty',
    position: 'RB',
    college: 'Boise State',
    conference: 'Mountain West',
    classYear: 'Junior',
    height: '5-9',
    weight: 215,
    paiScore: 82,
    tier: 'TOP_15',
    performance: 84,
    athleticism: 89,
    intangibles: 80,
    overallRank: 6,
    positionRank: 1,
    trend: 'DOWN',
    nflTeam: 'Las Vegas Raiders',
    draftPick: '1.06',
    rookieStats: '{"rushingYards":"892","rushingTDs":"6","yardsPerCarry":"3.8","receptions":"22","receivingYards":"168","fumbles":"3"}',
    rookieGrade: 55,
    rookieAssessment: 'The Raiders\' top-10 RB pick has been widely criticized. Behind a terrible OL, Jeanty could not replicate his college dominance. The 3-14 record tells the story.',
    scoutMemo: 'Raiders reached for a RB at #6 — one of the moves that got Pete Carroll fired. RB positional value debate vindicated.',
    comparisons: 'Trent Richardson (cautionary)',
  },
  {
    firstName: 'Mason',
    lastName: 'Graham',
    position: 'DT',
    college: 'Michigan',
    conference: 'Big Ten',
    classYear: 'Junior',
    height: '6-3',
    weight: 318,
    paiScore: 90,
    tier: 'TOP_15',
    performance: 90,
    athleticism: 88,
    intangibles: 91,
    overallRank: 7,
    positionRank: 1,
    trend: 'UP',
    nflTeam: 'New York Jets',
    draftPick: '1.07',
    rookieStats: '{"sacks":"5","TFLs":"11","tackles":"48","pressures":"34","pffGrade":"78.8"}',
    rookieGrade: 78,
    rookieAssessment: 'Steady, reliable DT who anchored the Jets interior. Good not great rookie year but the foundation is there for a long career.',
    scoutMemo: 'Michigan DT taken #7. Consistent performer despite the Jets\' poor overall record.',
    comparisons: 'DeForest Buckner (trajectory)',
  },
  {
    firstName: 'Kelvin',
    lastName: 'Banks Jr.',
    position: 'OT',
    college: 'Texas',
    conference: 'SEC',
    classYear: 'Junior',
    height: '6-4',
    weight: 320,
    paiScore: 89,
    tier: 'TOP_15',
    performance: 88,
    athleticism: 86,
    intangibles: 90,
    overallRank: 8,
    positionRank: 1,
    trend: 'STEADY',
    nflTeam: 'Carolina Panthers',
    draftPick: '1.08',
    rookieStats: '{"gamesStarted":"16","sacksAllowed":"3","penaltiesPerGame":"0.4","pffGrade":"74.2"}',
    rookieGrade: 74,
    rookieAssessment: 'Solid rookie year at left tackle. Protected Bryce Young well and showed improvement throughout the season. Not flashy but steady.',
    scoutMemo: 'Texas OT taken #8. Reliable blindside protector from Day 1.',
    comparisons: 'Tyron Smith (early career)',
  },
];

// Keep backward-compatible export name
export const REDRAFT_2025_PROSPECTS = REDRAFT_2025_CLASS;

// ─────────────────────────────────────────────────────────────
// 2024 Redraft — second-year re-evaluation
// Players from the 2024 NFL Draft now in their second NFL season
// ─────────────────────────────────────────────────────────────

export const REDRAFT_2024_CLASS: RedraftProspect[] = [
  {
    firstName: 'Caleb',
    lastName: 'Williams',
    position: 'QB',
    college: 'USC',
    conference: 'Big Ten',
    classYear: 'Senior',
    height: '6-1',
    weight: 215,
    paiScore: 90,
    tier: 'TOP_5',
    performance: 88,
    athleticism: 92,
    intangibles: 90,
    overallRank: 1,
    positionRank: 1,
    trend: 'STEADY',
    nflTeam: 'Chicago Bears',
    draftPick: '1.01',
    rookieStats: '{"completionPct":"63.1%","passingYards":"3542","passingTDs":"22","interceptions":"10","qbr":"72.8","wins":"7"}',
    rookieGrade: 72,
    rookieAssessment: 'Showed flashes of brilliance but struggled with consistency behind a shaky OL. Second-half surge gives hope. Needs better protection and weapons.',
    scoutMemo: 'Went #1 overall. Had typical rookie QB struggles but showed enough late in the season to justify the pick.',
    comparisons: 'Justin Fields (Year 1)',
  },
  {
    firstName: 'Jayden',
    lastName: 'Daniels',
    position: 'QB',
    college: 'LSU',
    conference: 'SEC',
    classYear: 'Senior',
    height: '6-4',
    weight: 210,
    paiScore: 94,
    tier: 'TOP_5',
    performance: 94,
    athleticism: 95,
    intangibles: 92,
    overallRank: 2,
    positionRank: 2,
    trend: 'UP',
    nflTeam: 'Washington Commanders',
    draftPick: '1.02',
    rookieStats: '{"completionPct":"69.2%","passingYards":"3568","passingTDs":"25","interceptions":"9","rushingYards":"891","rushingTDs":"6","qbr":"82.4"}',
    rookieGrade: 90,
    rookieAssessment: 'OROY frontrunner. Led Washington to the playoffs as a rookie. Dual-threat ability translated immediately. Franchise QB found.',
    scoutMemo: 'Best rookie QB season since Justin Herbert. Dual-threat game translated perfectly to the NFL.',
    comparisons: 'Lamar Jackson,Kyler Murray',
  },
  {
    firstName: 'Drake',
    lastName: 'Maye',
    position: 'QB',
    college: 'North Carolina',
    conference: 'ACC',
    classYear: 'Junior',
    height: '6-4',
    weight: 230,
    paiScore: 86,
    tier: 'TOP_5',
    performance: 82,
    athleticism: 88,
    intangibles: 87,
    overallRank: 3,
    positionRank: 3,
    trend: 'STEADY',
    nflTeam: 'New England Patriots',
    draftPick: '1.03',
    rookieStats: '{"completionPct":"61.8%","passingYards":"2884","passingTDs":"16","interceptions":"12","qbr":"68.5"}',
    rookieGrade: 65,
    rookieAssessment: 'Rough landing spot. Patriots lack weapons and OL talent. Showed arm talent and toughness but needs a complete overhaul around him.',
    scoutMemo: 'Talent is real but the situation in New England is dire. Needs help everywhere.',
    comparisons: 'Sam Darnold (situation)',
    injuryNote: 'Missed 3 games with knee contusion',
  },
  {
    firstName: 'Marvin',
    lastName: 'Harrison Jr.',
    position: 'WR',
    college: 'Ohio State',
    conference: 'Big Ten',
    classYear: 'Junior',
    height: '6-4',
    weight: 205,
    paiScore: 92,
    tier: 'TOP_5',
    performance: 88,
    athleticism: 90,
    intangibles: 93,
    overallRank: 4,
    positionRank: 1,
    trend: 'STEADY',
    nflTeam: 'Arizona Cardinals',
    draftPick: '1.04',
    rookieStats: '{"receptions":"68","receivingYards":"1042","receivingTDs":"8","yardsPerCatch":"15.3"}',
    rookieGrade: 80,
    rookieAssessment: 'Started slow but finished strong with Kyler Murray finding chemistry. Elite route-running translated. WR1 production incoming Year 2.',
    scoutMemo: 'Proved he can be a #1 WR in the NFL. Chemistry with Kyler Murray took time but the talent is undeniable.',
    comparisons: 'Marvin Harrison Sr. (ceiling)',
  },
  {
    firstName: 'Joe',
    lastName: 'Alt',
    position: 'OT',
    college: 'Notre Dame',
    conference: 'Independent',
    classYear: 'Junior',
    height: '6-8',
    weight: 322,
    paiScore: 94,
    tier: 'TOP_5',
    performance: 95,
    athleticism: 90,
    intangibles: 95,
    overallRank: 5,
    positionRank: 1,
    trend: 'UP',
    nflTeam: 'Los Angeles Chargers',
    draftPick: '1.05',
    rookieStats: '{"gamesStarted":"17","sacksAllowed":"2","penaltiesPerGame":"0.2","pffGrade":"88.4"}',
    rookieGrade: 93,
    rookieAssessment: 'Best rookie OL in a decade. Immediately became the Chargers\' best OL and a top-10 tackle in the NFL. Franchise cornerstone.',
    scoutMemo: 'Lived up to every bit of the hype. Elite from Week 1. All-Pro caliber already.',
    comparisons: 'Quenton Nelson (impact)',
  },
  {
    firstName: 'Malik',
    lastName: 'Nabers',
    position: 'WR',
    college: 'LSU',
    conference: 'SEC',
    classYear: 'Junior',
    height: '6-0',
    weight: 200,
    paiScore: 91,
    tier: 'TOP_15',
    performance: 90,
    athleticism: 93,
    intangibles: 89,
    overallRank: 6,
    positionRank: 2,
    trend: 'UP',
    nflTeam: 'New York Giants',
    draftPick: '1.06',
    rookieStats: '{"receptions":"82","receivingYards":"1178","receivingTDs":"7","yardsPerCatch":"14.4"}',
    rookieGrade: 85,
    rookieAssessment: 'Dominant rookie WR season despite inconsistent QB play. Route running and separation are already elite. Imagine him with a franchise QB.',
    scoutMemo: 'LSU WR pipeline delivers again. Nabers was the best offensive player on the Giants from Day 1.',
    comparisons: "Ja'Marr Chase (trajectory)",
    injuryNote: 'Brief concussion protocol absence Week 4',
  },
  {
    firstName: 'Quinyon',
    lastName: 'Mitchell',
    position: 'CB',
    college: 'Toledo',
    conference: 'MAC',
    classYear: 'Junior',
    height: '5-11',
    weight: 195,
    paiScore: 88,
    tier: 'FIRST_ROUND',
    performance: 88,
    athleticism: 90,
    intangibles: 86,
    overallRank: 7,
    positionRank: 1,
    trend: 'UP',
    nflTeam: 'Philadelphia Eagles',
    draftPick: '1.22',
    rookieStats: '{"interceptions":"4","passBreakups":"15","tackles":"56","pffCovGrade":"78.2"}',
    rookieGrade: 82,
    rookieAssessment: 'Stepped into a starting role immediately and held his own. Ball production was elite for a rookie. Eagles secondary got a cornerstone.',
    scoutMemo: 'Small-school prospect who proved he belongs. Physical, competitive, and productive from Day 1.',
    comparisons: 'Sauce Gardner (trajectory)',
  },
];

// ─────────────────────────────────────────────────────────────
// NFL Team Needs — 2026 Draft Order (FINAL)
// Seahawks won Super Bowl LX over Patriots.
// Raiders pick #1 (3-14, easiest SOS tiebreaker).
// 4 teams traded away 1st rounders: ATL, GB, JAX, IND.
// Cowboys (2 picks), Rams (2 picks), Jets (2 picks), Browns (2 picks).
// ─────────────────────────────────────────────────────────────

export interface TeamNeed {
  team: string;
  abbrev: string;
  projectedPick: number;
  primaryNeeds: string[];
  secondaryNeeds: string[];
  tradeLikelihood: 'LOW' | 'MEDIUM' | 'HIGH';
  tradeNote?: string;
}

export const NFL_TEAM_NEEDS_2026: TeamNeed[] = [
  { team: 'Las Vegas Raiders', abbrev: 'LV', projectedPick: 1, primaryNeeds: ['QB', 'EDGE', 'OT'], secondaryNeeds: ['CB', 'WR'], tradeLikelihood: 'LOW', tradeNote: 'Locked in on Fernando Mendoza. New HC hire after firing Pete Carroll.' },
  { team: 'New York Jets', abbrev: 'NYJ', projectedPick: 2, primaryNeeds: ['EDGE', 'WR', 'S'], secondaryNeeds: ['QB', 'OT'], tradeLikelihood: 'MEDIUM', tradeNote: 'Tore it down at trade deadline. 4 of top 50 picks. Started 3 QBs in 2025.' },
  { team: 'Arizona Cardinals', abbrev: 'ARI', projectedPick: 3, primaryNeeds: ['EDGE', 'OT', 'CB'], secondaryNeeds: ['DT', 'LB'], tradeLikelihood: 'MEDIUM' },
  { team: 'Tennessee Titans', abbrev: 'TEN', projectedPick: 4, primaryNeeds: ['LB', 'OT', 'WR'], secondaryNeeds: ['EDGE', 'CB'], tradeLikelihood: 'LOW', tradeNote: 'Sanders at QB, need to build around him.' },
  { team: 'New York Giants', abbrev: 'NYG', projectedPick: 5, primaryNeeds: ['OT', 'EDGE', 'DT'], secondaryNeeds: ['CB', 'LB'], tradeLikelihood: 'HIGH', tradeNote: 'Cam Ward struggling — could trade down for capital.' },
  { team: 'Cleveland Browns', abbrev: 'CLE', projectedPick: 6, primaryNeeds: ['WR', 'OT', 'QB'], secondaryNeeds: ['EDGE', 'S'], tradeLikelihood: 'MEDIUM', tradeNote: 'Also pick 24 (via JAX). Hunter is the CB — need offensive weapons.' },
  { team: 'Washington Commanders', abbrev: 'WAS', projectedPick: 7, primaryNeeds: ['EDGE', 'DT', 'CB'], secondaryNeeds: ['OT', 'LB'], tradeLikelihood: 'LOW', tradeNote: 'Daniels is the franchise QB. Build the defense.' },
  { team: 'New Orleans Saints', abbrev: 'NO', projectedPick: 8, primaryNeeds: ['QB', 'WR', 'OT'], secondaryNeeds: ['EDGE', 'CB'], tradeLikelihood: 'MEDIUM' },
  { team: 'Cincinnati Bengals', abbrev: 'CIN', projectedPick: 9, primaryNeeds: ['OT', 'DT', 'CB'], secondaryNeeds: ['EDGE', 'LB'], tradeLikelihood: 'LOW' },
  { team: 'Kansas City Chiefs', abbrev: 'KC', projectedPick: 10, primaryNeeds: ['RB', 'WR', 'CB'], secondaryNeeds: ['EDGE', 'OT'], tradeLikelihood: 'LOW', tradeNote: 'Kiper mocked RB Jeremiyah Love here.' },
  { team: 'Miami Dolphins', abbrev: 'MIA', projectedPick: 11, primaryNeeds: ['QB', 'OT', 'EDGE'], secondaryNeeds: ['CB', 'LB'], tradeLikelihood: 'MEDIUM' },
  { team: 'Dallas Cowboys', abbrev: 'DAL', projectedPick: 12, primaryNeeds: ['S', 'CB', 'EDGE'], secondaryNeeds: ['DT', 'LB'], tradeLikelihood: 'LOW', tradeNote: 'Also pick 20 (via GB/Parsons trade). Rebuild the defense.' },
  { team: 'Los Angeles Rams', abbrev: 'LAR', projectedPick: 13, primaryNeeds: ['QB', 'CB', 'EDGE'], secondaryNeeds: ['OT', 'WR'], tradeLikelihood: 'HIGH', tradeNote: 'Via ATL. Also pick 29. Stafford retirement uncertain. Could trade up for QB.' },
  { team: 'Baltimore Ravens', abbrev: 'BAL', projectedPick: 14, primaryNeeds: ['WR', 'EDGE', 'CB'], secondaryNeeds: ['OT', 'S'], tradeLikelihood: 'LOW' },
  { team: 'Tampa Bay Buccaneers', abbrev: 'TB', projectedPick: 15, primaryNeeds: ['DT', 'EDGE', 'CB'], secondaryNeeds: ['OT', 'S'], tradeLikelihood: 'LOW' },
  { team: 'New York Jets', abbrev: 'NYJ', projectedPick: 16, primaryNeeds: ['WR', 'OT', 'CB'], secondaryNeeds: ['QB', 'LB'], tradeLikelihood: 'MEDIUM', tradeNote: 'Via IND (Sauce Gardner trade). Second first-rounder.' },
  { team: 'Detroit Lions', abbrev: 'DET', projectedPick: 17, primaryNeeds: ['CB', 'EDGE', 'DT'], secondaryNeeds: ['LB', 'S'], tradeLikelihood: 'MEDIUM' },
  { team: 'Minnesota Vikings', abbrev: 'MIN', projectedPick: 18, primaryNeeds: ['OT', 'CB', 'EDGE'], secondaryNeeds: ['DT', 'S'], tradeLikelihood: 'LOW' },
  { team: 'Carolina Panthers', abbrev: 'CAR', projectedPick: 19, primaryNeeds: ['WR', 'EDGE', 'DT'], secondaryNeeds: ['CB', 'OT'], tradeLikelihood: 'LOW' },
  { team: 'Dallas Cowboys', abbrev: 'DAL', projectedPick: 20, primaryNeeds: ['LB', 'EDGE', 'DT'], secondaryNeeds: ['CB', 'S'], tradeLikelihood: 'LOW', tradeNote: 'Via GB (Micah Parsons trade). Second first-rounder.' },
  { team: 'Pittsburgh Steelers', abbrev: 'PIT', projectedPick: 21, primaryNeeds: ['QB', 'OT', 'WR'], secondaryNeeds: ['CB', 'DT'], tradeLikelihood: 'HIGH', tradeNote: 'Likely target: Ty Simpson, QB Alabama. Post-Tomlin rebuild.' },
  { team: 'Los Angeles Chargers', abbrev: 'LAC', projectedPick: 22, primaryNeeds: ['WR', 'EDGE', 'CB'], secondaryNeeds: ['OT', 'LB'], tradeLikelihood: 'LOW' },
  { team: 'Philadelphia Eagles', abbrev: 'PHI', projectedPick: 23, primaryNeeds: ['CB', 'LB', 'EDGE'], secondaryNeeds: ['S', 'WR'], tradeLikelihood: 'MEDIUM' },
  { team: 'Cleveland Browns', abbrev: 'CLE', projectedPick: 24, primaryNeeds: ['OT', 'WR', 'DT'], secondaryNeeds: ['S', 'LB'], tradeLikelihood: 'MEDIUM', tradeNote: 'Via JAX. Second first-rounder.' },
  { team: 'Chicago Bears', abbrev: 'CHI', projectedPick: 25, primaryNeeds: ['OT', 'WR', 'CB'], secondaryNeeds: ['EDGE', 'RB'], tradeLikelihood: 'MEDIUM' },
  { team: 'Buffalo Bills', abbrev: 'BUF', projectedPick: 26, primaryNeeds: ['WR', 'OT', 'DT'], secondaryNeeds: ['CB', 'EDGE'], tradeLikelihood: 'LOW' },
  { team: 'San Francisco 49ers', abbrev: 'SF', projectedPick: 27, primaryNeeds: ['QB', 'OT', 'CB'], secondaryNeeds: ['WR', 'S'], tradeLikelihood: 'MEDIUM' },
  { team: 'Houston Texans', abbrev: 'HOU', projectedPick: 28, primaryNeeds: ['OT', 'EDGE', 'CB'], secondaryNeeds: ['DT', 'S'], tradeLikelihood: 'LOW' },
  { team: 'Los Angeles Rams', abbrev: 'LAR', projectedPick: 29, primaryNeeds: ['CB', 'WR', 'EDGE'], secondaryNeeds: ['OT', 'DT'], tradeLikelihood: 'MEDIUM', tradeNote: 'Own pick. Second first-rounder.' },
  { team: 'Denver Broncos', abbrev: 'DEN', projectedPick: 30, primaryNeeds: ['WR', 'OT', 'CB'], secondaryNeeds: ['EDGE', 'TE'], tradeLikelihood: 'MEDIUM' },
  { team: 'New England Patriots', abbrev: 'NE', projectedPick: 31, primaryNeeds: ['WR', 'OT', 'CB'], secondaryNeeds: ['DT', 'LB'], tradeLikelihood: 'LOW', tradeNote: 'Super Bowl runner-up. Carter is the star, need more weapons for Maye.' },
  { team: 'Seattle Seahawks', abbrev: 'SEA', projectedPick: 32, primaryNeeds: ['EDGE', 'CB', 'DT'], secondaryNeeds: ['OT', 'WR'], tradeLikelihood: 'LOW', tradeNote: 'Super Bowl LX champions. Pick last.' },
];
