/**
 * Per|Form Prospect Data — 2026 Recruiting Class
 *
 * Top high school recruits and transfer portal additions for the
 * 2026 recruiting cycle. P.A.I. (Performance, Athleticism, Intangibles)
 * scoring, adversarial debate results, and scouting memos.
 *
 * Prospects can be enriched with live data via the /api/perform/enrich
 * endpoint using Brave Search.
 */

export interface SeedProspect {
  firstName: string;
  lastName: string;
  position: string;
  classYear: string;
  school: string;
  state: string;
  pool: string;
  height?: string;
  weight?: number;
  gpa?: number;
  paiScore: number;
  tier: string;
  performance: number;
  athleticism: number;
  intangibles: number;
  nationalRank: number;
  stateRank: number;
  positionRank: number;
  trend: string;
  previousRank?: number;
  nilEstimate: string;
  scoutMemo: string;
  tags: string[];
  comparisons: string[];
  stats: Record<string, string | number>;
  bullCase: string;
  bearCase: string;
  mediationVerdict: string;
  debateWinner: string;
  stars?: number;
  enrichedBy?: string;
}

export const SEED_PROSPECTS: SeedProspect[] = [
  // ─── QB ────────────────────────────────────────────────────
  {
    firstName: 'Arch',
    lastName: 'Manning',
    position: 'QB',
    classYear: '2026 Draft',
    school: 'Texas',
    state: 'TX',
    pool: 'COLLEGE',
    height: '6-4',
    weight: 225,
    paiScore: 98,
    tier: 'ELITE',
    performance: 96,
    athleticism: 97,
    intangibles: 99,
    nationalRank: 1,
    stateRank: 1,
    positionRank: 1,
    trend: 'UP',
    nilEstimate: '$4.5M',
    scoutMemo: 'The premier 2026 NFL Draft prospect. Generational IQ and processing paired with underrated athleticism. Stepped into the Texas offense seamlessly.',
    tags: ['5-Star', '1.01 Pick', 'Manning Dynasty'],
    comparisons: ['Peyton Manning', 'Andrew Luck'],
    stats: { passingYards: 3100, passingTDs: 32, rushingYards: 250, rushingTDs: 5, completionPct: '69.5%' },
    bullCase: 'Highest floor of any prospect in a decade. NFL-ready processing, elite mechanics, and unexpected mobility.',
    bearCase: 'Enormous expectations bring unprecedented pressure. Will he elevate a struggling NFL franchise immediately?',
    mediationVerdict: 'Bull case wins easily. The bloodline is proven and his Texas tape confirms elite tiering.',
    debateWinner: 'BULL',
    stars: 5,
  },
  {
    firstName: 'Bryce',
    lastName: 'Underwood',
    position: 'QB',
    classYear: "'26",
    school: 'Belleville',
    state: 'MI',
    pool: 'HIGH_SCHOOL',
    height: '6-4',
    weight: 215,
    gpa: 3.7,
    paiScore: 97,
    tier: 'ELITE',
    performance: 98,
    athleticism: 96,
    intangibles: 97,
    nationalRank: 1,
    stateRank: 1,
    positionRank: 1,
    trend: 'STEADY',
    nilEstimate: '$4.2M',
    scoutMemo: 'Generational dual-threat QB. Elite arm talent with 4.5 speed. Committed to Michigan — program-defining get for Sherrone Moore.',
    tags: ['5-Star', 'No. 1 Overall', 'Dual-Threat', 'Michigan Commit'],
    comparisons: ['Vince Young', 'Cam Newton'],
    stats: { passingYards: 3850, passingTDs: 48, rushingYards: 1100, rushingTDs: 18, completionPct: '71.2%' },
    bullCase: 'Best QB prospect since Trevor Lawrence. Arm, legs, and football IQ all grade elite. Could start Day 1 as a freshman.',
    bearCase: 'Michigan offense historically has not maximized elite QBs. Will the system adapt to his skill set?',
    mediationVerdict: 'Bull case wins. Talent transcends system — Michigan will build around him.',
    debateWinner: 'BULL',
    stars: 5,
  },
  {
    firstName: 'Keelon',
    lastName: 'Russell',
    position: 'QB',
    classYear: "'26",
    school: 'Duncanville',
    state: 'TX',
    pool: 'HIGH_SCHOOL',
    height: '6-2',
    weight: 200,
    gpa: 3.5,
    paiScore: 95,
    tier: 'ELITE',
    performance: 96,
    athleticism: 93,
    intangibles: 95,
    nationalRank: 3,
    stateRank: 1,
    positionRank: 2,
    trend: 'UP',
    previousRank: 5,
    nilEstimate: '$3.5M',
    scoutMemo: 'Elite pocket presence with escapability. Texas powerhouse QB who thrives under pressure. Oregon commit.',
    tags: ['5-Star', 'Oregon Commit', 'Pro-Style', 'Texas Mr. Football'],
    comparisons: ['Dak Prescott', 'Jalen Hurts'],
    stats: { passingYards: 3600, passingTDs: 42, rushingYards: 680, rushingTDs: 12, completionPct: '68.5%' },
    bullCase: 'Proven winner from big-time Texas program. Arm talent and decision-making are both top-tier.',
    bearCase: 'Slightly undersized. Oregon has had mixed results developing elite QBs recently.',
    mediationVerdict: 'Bull case wins. His processing speed and poise set him apart.',
    debateWinner: 'BULL',
    stars: 5,
  },
  {
    firstName: 'Tavien',
    lastName: 'St. Clair',
    position: 'QB',
    classYear: "'26",
    school: 'Bellefontaine',
    state: 'OH',
    pool: 'HIGH_SCHOOL',
    height: '6-4',
    weight: 220,
    gpa: 3.6,
    paiScore: 93,
    tier: 'ELITE',
    performance: 94,
    athleticism: 91,
    intangibles: 93,
    nationalRank: 8,
    stateRank: 1,
    positionRank: 3,
    trend: 'STEADY',
    nilEstimate: '$2.8M',
    scoutMemo: 'Prototypical Big Ten QB build. Cannon arm, great size, and Ohio roots. Ohio State commit locks down home-state QB.',
    tags: ['5-Star', 'Ohio State Commit', 'Pro-Style', 'Power Arm'],
    comparisons: ['Justin Herbert', 'Joe Burrow'],
    stats: { passingYards: 3400, passingTDs: 40, rushingYards: 450, rushingTDs: 8, completionPct: '67.8%' },
    bullCase: 'Has the arm and frame NFL scouts dream about. Ryan Day QB room is the best finishing school in CFB.',
    bearCase: 'Small-school competition. Has not faced elite defensive talent weekly.',
    mediationVerdict: 'Bull case edges it. Ohio State develops QBs at an elite level now.',
    debateWinner: 'BULL',
    stars: 5,
  },
  {
    firstName: 'Faizon',
    lastName: 'Brandon',
    position: 'QB',
    classYear: "'26",
    school: 'Grimsley',
    state: 'NC',
    pool: 'HIGH_SCHOOL',
    height: '6-4',
    weight: 195,
    gpa: 3.8,
    paiScore: 96,
    tier: 'ELITE',
    performance: 97,
    athleticism: 95,
    intangibles: 96,
    nationalRank: 1,
    stateRank: 1,
    positionRank: 1,
    trend: 'UP',
    nilEstimate: '$4.8M',
    scoutMemo: 'The new No. 1 overall prospect for 2026. Rare arm flexibility and elite processing. Major SEC/Ohio State target.',
    tags: ['5-Star', 'No. 1 Prospect', 'Dual-Threat', 'Elite Arm'],
    comparisons: ['Patrick Mahomes', 'Lamar Jackson'],
    stats: { passingYards: 3100, passingTDs: 36, rushingYards: 550, rushingTDs: 9 },
    bullCase: 'Highest ceiling in the class. Uncanny ability to make off-platform throws.',
    bearCase: 'Lean frame will need to hold up against SEC-level speed and physicality.',
    mediationVerdict: 'Bull case wins. His natural talent is once-in-a-decade.',
    debateWinner: 'BULL',
    stars: 5,
  },
  {
    firstName: 'Dia',
    lastName: 'Bell',
    position: 'QB',
    classYear: "'26",
    school: 'American Heritage',
    state: 'FL',
    pool: 'HIGH_SCHOOL',
    height: '6-2',
    weight: 195,
    gpa: 3.9,
    paiScore: 94,
    tier: 'ELITE',
    performance: 95,
    athleticism: 92,
    intangibles: 95,
    nationalRank: 12,
    stateRank: 2,
    positionRank: 4,
    trend: 'STEADY',
    nilEstimate: '$2.2M',
    scoutMemo: 'Texas commit. Son of NBA veteran Charlie Bell. Elite IQ and ball placement. Prototype for the modern air raid.',
    tags: ['5-Star', 'Texas Commit', 'NBA Bloodline', 'Pinpoint Accuracy'],
    comparisons: ['Joe Burrow', 'Mac Jones'],
    stats: { passingYards: 2900, passingTDs: 32, completionPct: '73.5%' },
    bullCase: 'IQ and accuracy are the most bankable traits for college success. Steve Sarkisian will maximize him.',
    bearCase: 'Average arm strength compared to Underwood or Brandon.',
    mediationVerdict: 'Bull case wins. Accuracy wins championships in Austin.',
    debateWinner: 'BULL',
    stars: 5,
  },

  // ─── WR ────────────────────────────────────────────────────
  {
    firstName: 'Jeremiah',
    lastName: 'Smith',
    position: 'WR',
    classYear: '2026 Sophomore',
    school: 'Ohio State',
    state: 'OH',
    pool: 'COLLEGE',
    height: '6-3',
    weight: 215,
    paiScore: 99,
    tier: 'ELITE',
    performance: 99,
    athleticism: 98,
    intangibles: 98,
    nationalRank: 1,
    stateRank: 1,
    positionRank: 1,
    trend: 'UP',
    nilEstimate: '$3.5M',
    scoutMemo: 'The defining WR talent of his generation. True sophomore with Julio Jones size and Justin Jefferson route running.',
    tags: ['5-Star', 'All-American', 'Buckeye Star'],
    comparisons: ['Julio Jones', 'Calvin Johnson'],
    stats: { receptions: 85, receivingYards: 1250, receivingTDs: 14, yardsPerCatch: 14.7 },
    bullCase: 'Will be the first WR taken in the draft whenever he declares. Transcends system.',
    bearCase: 'None. Only injuries can derail his trajectory.',
    mediationVerdict: 'Unanimous Bull.',
    debateWinner: 'BULL',
    stars: 5,
  },

  // ─── EDGE / DL ─────────────────────────────────────────────
  {
    firstName: 'Jahkeem',
    lastName: 'Stewart',
    position: 'EDGE',
    classYear: "'26",
    school: 'Evergreen',
    state: 'LA',
    pool: 'HIGH_SCHOOL',
    height: '6-5',
    weight: 265,
    gpa: 3.3,
    paiScore: 96,
    tier: 'ELITE',
    performance: 97,
    athleticism: 96,
    intangibles: 94,
    nationalRank: 2,
    stateRank: 1,
    positionRank: 1,
    trend: 'STEADY',
    nilEstimate: '$3.8M',
    scoutMemo: 'Freak-of-nature edge rusher. NFL-ready body at 17. The most physically dominant HS defender in years.',
    tags: ['5-Star', 'No. 2 Overall', 'Pass Rusher', 'LSU Lean'],
    comparisons: ['Jadeveon Clowney', 'Myles Garrett'],
    stats: { sacks: 22, TFLs: 38, forcedFumbles: 8, tackles: 95 },
    bullCase: 'Generational physical specimen. Could be a 3-year starter and top-5 NFL pick. Pass rush wins games.',
    bearCase: 'Raw technique — relies heavily on physical dominance. May need refinement against college OTs.',
    mediationVerdict: 'Bull case wins. You cannot teach this size/speed combination.',
    debateWinner: 'BULL',
    stars: 5,
  },
  {
    firstName: 'Colin',
    lastName: 'Simmons',
    position: 'EDGE',
    classYear: "'26",
    school: 'Duncanville',
    state: 'TX',
    pool: 'HIGH_SCHOOL',
    height: '6-4',
    weight: 245,
    gpa: 3.4,
    paiScore: 94,
    tier: 'ELITE',
    performance: 95,
    athleticism: 94,
    intangibles: 92,
    nationalRank: 5,
    stateRank: 2,
    positionRank: 2,
    trend: 'UP',
    previousRank: 8,
    nilEstimate: '$2.5M',
    scoutMemo: 'Explosive first step and violent hands. Texas commit who pairs with current DL room to form fearsome front.',
    tags: ['5-Star', 'Texas Commit', 'Speed Rusher', 'Motor'],
    comparisons: ['DeMarcus Ware', 'Von Miller'],
    stats: { sacks: 18, TFLs: 32, forcedFumbles: 5, tackles: 82 },
    bullCase: 'Rare burst off the edge. Texas defensive line could be historic with this addition.',
    bearCase: 'Needs to add functional strength to hold up against power run schemes.',
    mediationVerdict: 'Bull case wins. Speed kills, and he has elite closing speed.',
    debateWinner: 'BULL',
    stars: 5,
  },

  // ─── WR ────────────────────────────────────────────────────
  {
    firstName: 'Dakorien',
    lastName: 'Moore',
    position: 'WR',
    classYear: "'26",
    school: 'Duncanville',
    state: 'TX',
    pool: 'HIGH_SCHOOL',
    height: '6-0',
    weight: 190,
    gpa: 3.5,
    paiScore: 94,
    tier: 'ELITE',
    performance: 95,
    athleticism: 95,
    intangibles: 91,
    nationalRank: 4,
    stateRank: 3,
    positionRank: 1,
    trend: 'STEADY',
    nilEstimate: '$2.8M',
    scoutMemo: 'Explosive route-runner with elite YAC ability. Game-breaking speed and excellent ball tracking. LSU commit.',
    tags: ['5-Star', 'LSU Commit', 'Speed', 'Playmaker'],
    comparisons: ["Ja'Marr Chase", 'Justin Jefferson'],
    stats: { receptions: 78, receivingYards: 1650, receivingTDs: 22, yardsPerCatch: 21.2 },
    bullCase: 'LSU WR pipeline is the best in CFB. His speed and route-running combo is rare at the HS level.',
    bearCase: 'Slight frame — may need to add 10-15 lbs without losing explosiveness.',
    mediationVerdict: 'Bull case wins. LSU knows how to develop receivers better than anyone.',
    debateWinner: 'BULL',
    stars: 5,
  },
  {
    firstName: 'Chris',
    lastName: 'Henry Jr.',
    position: 'WR',
    classYear: "'26",
    school: 'Mater Dei',
    state: 'CA',
    pool: 'HIGH_SCHOOL',
    height: '6-5',
    weight: 200,
    gpa: 3.6,
    paiScore: 98,
    tier: 'ELITE',
    performance: 98,
    athleticism: 97,
    intangibles: 96,
    nationalRank: 2,
    stateRank: 1,
    positionRank: 1,
    trend: 'STEADY',
    nilEstimate: '$5.2M',
    scoutMemo: 'The crown jewel of the Ohio State 2026 class. Prototypical WR1 build with elite hands and body control. Son of NFL great Chris Henry.',
    tags: ['5-Star', 'Ohio State Commit', 'Legacy', 'WR1'],
    comparisons: ['Marvin Harrison Jr.', 'Randy Moss'],
    stats: { receptions: 82, receivingYards: 1720, receivingTDs: 24, yardsPerCatch: 20.9 },
    bullCase: 'Better prospect than Marvin Harrison Jr. was at this stage. Physically dominant and technically sound.',
    bearCase: 'Handling the immense expectations of being a superstar legacy at OSU.',
    mediationVerdict: 'Bull case wins. He is undeniable.',
    debateWinner: 'BULL',
    stars: 5,
  },
  {
    firstName: 'Jeremiah',
    lastName: 'Smith',
    position: 'WR',
    classYear: "'24",
    school: 'Ohio State',
    state: 'FL',
    pool: 'COLLEGE',
    height: '6-3',
    weight: 215,
    gpa: 3.5,
    paiScore: 99,
    tier: 'ELITE',
    performance: 99,
    athleticism: 98,
    intangibles: 99,
    nationalRank: 1,
    stateRank: 1,
    positionRank: 1,
    trend: 'STEADY',
    nilEstimate: '$5.5M',
    scoutMemo: 'The most polished freshman WR in modern history. Immediate superstar at Ohio State. Draft-eligible lock for Top 5 in 2027.',
    tags: ['5-Star', 'Freshman All-American', 'Superstar', 'WR1'],
    comparisons: ['Julio Jones', 'Marvin Harrison Jr.'],
    stats: { receptions: 8 }, // stats truncated for seed
    bullCase: 'Heiseman-caliber talent. Transcendent hands and route-running.',
    bearCase: 'None. He is the standard.',
    mediationVerdict: 'Bull case wins. Generational talent.',
    debateWinner: 'BULL',
    stars: 5,
  },
  {
    firstName: 'Julian',
    lastName: 'Sayin',
    position: 'QB',
    classYear: "'24",
    school: 'Ohio State',
    state: 'CA',
    pool: 'COLLEGE',
    height: '6-1',
    weight: 200,
    gpa: 4.0,
    paiScore: 92,
    tier: 'ELITE',
    performance: 94,
    athleticism: 88,
    intangibles: 96,
    nationalRank: 3,
    stateRank: 1,
    positionRank: 1,
    trend: 'STEADY',
    nilEstimate: '$2.1M',
    scoutMemo: 'Elite processing and accuracy. The future of the Buckeyes at QB. Transferred from Bama after Saban retirement.',
    tags: ['5-Star', 'Precision Passer', 'Highest IQ', 'Bama Transfer'],
    comparisons: ['Joe Burrow', 'Mac Jones'],
    stats: { completionPct: '74.5%' },
    bullCase: 'Most accurate passer in his class. IQ is off the charts.',
    bearCase: 'Size could be a factor in the pocket against elite SEC/B1G pass rush.',
    mediationVerdict: 'Bull case wins. Accuracy is the most bankable trait.',
    debateWinner: 'BULL',
    stars: 5,
  },
  {
    firstName: 'Jeremiah',
    lastName: 'McClellan',
    position: 'WR',
    classYear: "'26",
    school: 'University City',
    state: 'MO',
    pool: 'HIGH_SCHOOL',
    height: '6-1',
    weight: 195,
    gpa: 3.4,
    paiScore: 92,
    tier: 'ELITE',
    performance: 93,
    athleticism: 92,
    intangibles: 90,
    nationalRank: 10,
    stateRank: 1,
    positionRank: 2,
    trend: 'UP',
    previousRank: 14,
    nilEstimate: '$2.0M',
    scoutMemo: 'Physical WR who dominates contested catches. Elite body control and strong hands. Oklahoma commit.',
    tags: ['5-Star', 'Oklahoma Commit', 'Contested Catch', 'Physical'],
    comparisons: ['Mike Evans', 'DeAndre Hopkins'],
    stats: { receptions: 72, receivingYards: 1420, receivingTDs: 19, yardsPerCatch: 19.7 },
    bullCase: 'Rare combination of size, hands, and competitiveness. Will thrive in Big 12 with high-volume passing.',
    bearCase: 'Not a burner — may not separate consistently against elite press corners.',
    mediationVerdict: 'Bull case edges it. Contested-catch ability translates at every level.',
    debateWinner: 'BULL',
    stars: 5,
  },

  // ─── OL ────────────────────────────────────────────────────
  {
    firstName: 'David',
    lastName: 'Sanders Jr.',
    position: 'OT',
    classYear: "'25",
    school: 'Ohio State University',
    state: 'OH',
    pool: 'HIGH_SCHOOL',
    height: '6-6',
    weight: 290,
    gpa: 3.8,
    paiScore: 98,
    tier: 'ELITE',
    performance: 97,
    athleticism: 99,
    intangibles: 98,
    nationalRank: 1,
    stateRank: 1,
    positionRank: 1,
    trend: 'STEADY',
    nilEstimate: '$4.5M',
    scoutMemo: 'The #1 overall prospect in the nation. Transcendent athleticism for a 6-6 tackle. Per user: Committed to Ohio State.',
    tags: ['5-Star', 'No. 1 OT', 'Ohio State Commit', 'Elite Length'],
    comparisons: ['Laremy Tunsil', 'Trent Williams'],
    stats: { pancakeBlocks: 52, sacksAllowed: 0, penaltiesPerGame: 0.1 },
    bullCase: 'Highest ceiling of any OT prospect in a decade. 4.8 speed at 290 lbs. Potential #1 overall NFL pick.',
    bearCase: 'Needs to pack on 20-30 lbs for the Big Ten, but has the frame to do it easily.',
    mediationVerdict: 'Bull case wins. Rare physical gifts make him a consensus elite tackle.',
    debateWinner: 'BULL',
    stars: 5,
  },
  {
    firstName: 'Michael',
    lastName: 'Fasusi',
    position: 'OT',
    classYear: "'26",
    school: 'Lewisville',
    state: 'TX',
    pool: 'HIGH_SCHOOL',
    height: '6-6',
    weight: 310,
    gpa: 3.5,
    paiScore: 93,
    tier: 'ELITE',
    performance: 93,
    athleticism: 94,
    intangibles: 92,
    nationalRank: 6,
    stateRank: 4,
    positionRank: 1,
    trend: 'STEADY',
    nilEstimate: '$2.2M',
    scoutMemo: 'Massive tackle with surprising agility. Dominates in both run and pass protection. Texas commit locks down the blind side.',
    tags: ['5-Star', 'Texas Commit', 'Left Tackle', 'Mauler'],
    comparisons: ['Orlando Pace', 'Tyron Smith'],
    stats: { pancakeBlocks: 48, sacksAllowed: 0, penaltiesPerGame: 0.3 },
    bullCase: 'Day 1 starter at LT. NFL body with college-ready technique. Texas OL tradition.',
    bearCase: 'Weight management long-term. Needs to maintain athleticism as frame fills out.',
    mediationVerdict: 'Bull case wins. Franchise LT prospects are the rarest commodity.',
    debateWinner: 'BULL',
    stars: 5,
  },
  {
    firstName: 'David',
    lastName: 'Sanders Jr.',
    position: 'OT',
    classYear: "'26",
    school: 'Ohio State',
    state: 'NC',
    pool: 'HIGH_SCHOOL',
    height: '6-6',
    weight: 290,
    gpa: 3.8,
    paiScore: 96,
    tier: 'ELITE',
    performance: 96,
    athleticism: 97,
    intangibles: 95,
    nationalRank: 3,
    stateRank: 1,
    positionRank: 1,
    trend: 'UP',
    nilEstimate: '$3.5M',
    scoutMemo: 'Hyper-athletic tackle prospect with elite length. Moves like a tight end. User confirmed at Ohio State — massive win for Ryan Day on the trail.',
    tags: ['5-Star', 'Ohio State Commit', 'No. 1 OT', 'Athletic Freak'],
    comparisons: ['Laremy Tunsil', 'Trent Williams'],
    stats: { pancakeBlocks: 52, sacksAllowed: 0, penaltiesPerGame: 0.2 },
    bullCase: 'Highest ceiling of any tackle in the 2026 class. His lateral movement and recovery are generational.',
    bearCase: 'Needs to add another 20lbs of functional mass to handle Big Ten power. Transition period expected.',
    mediationVerdict: 'Bull case wins. Talent is undeniable; frames fill out, but movement like this is rare.',
    debateWinner: 'BULL',
    stars: 5,
  },
  {
    firstName: 'Douglas',
    lastName: 'Utu',
    position: 'OG',
    classYear: "'26",
    school: 'St. John Bosco',
    state: 'CA',
    pool: 'HIGH_SCHOOL',
    height: '6-5',
    weight: 320,
    gpa: 3.3,
    paiScore: 91,
    tier: 'ELITE',
    performance: 92,
    athleticism: 90,
    intangibles: 91,
    nationalRank: 12,
    stateRank: 1,
    positionRank: 2,
    trend: 'UP',
    previousRank: 18,
    nilEstimate: '$1.8M',
    scoutMemo: 'Dominant interior lineman from elite SoCal program. Nasty in run game with improving pass sets. USC commit.',
    tags: ['5-Star', 'USC Commit', 'Guard', 'Road Grader'],
    comparisons: ['Quenton Nelson', 'Zack Martin'],
    stats: { pancakeBlocks: 42, sacksAllowed: 1, penaltiesPerGame: 0.4 },
    bullCase: 'Plug-and-play starter at guard. USC needs interior OL badly, and he fills that immediately.',
    bearCase: 'Guard value is lower than tackle in the NFL draft — may limit NIL ceiling.',
    mediationVerdict: 'Bull case wins. Elite guards are hard to find and he is the best in the class.',
    debateWinner: 'BULL',
    stars: 5,
  },

  // ─── RB ────────────────────────────────────────────────────
  {
    firstName: 'Harlem',
    lastName: 'Berry',
    position: 'RB',
    classYear: "'26",
    school: 'many',
    state: 'LA',
    pool: 'HIGH_SCHOOL',
    height: '5-11',
    weight: 195,
    gpa: 3.4,
    paiScore: 93,
    tier: 'ELITE',
    performance: 94,
    athleticism: 95,
    intangibles: 89,
    nationalRank: 7,
    stateRank: 2,
    positionRank: 1,
    trend: 'UP',
    previousRank: 11,
    nilEstimate: '$2.5M',
    scoutMemo: 'Dynamic, lightning-fast RB. Sub-4.4 speed with wiggle and power. LSU commit adds explosive playmaker to backfield.',
    tags: ['5-Star', 'LSU Commit', 'Speed Back', 'Home Run Threat'],
    comparisons: ['Chris Johnson', 'Alvin Kamara'],
    stats: { rushingYards: 2850, rushingTDs: 38, yardsPerCarry: 9.8, receptions: 22, receivingYards: 380 },
    bullCase: 'Top-end speed is elite even by NFL standards. Dynamic in space and as receiver.',
    bearCase: 'Small-school competition in Louisiana. Durability at 195 lbs against SEC defenses.',
    mediationVerdict: 'Bull case wins. Speed is the one thing you can\'t teach, and his is elite.',
    debateWinner: 'BULL',
    stars: 5,
  },

  // ─── DB ────────────────────────────────────────────────────
  {
    firstName: 'Na\'eem',
    lastName: 'Offord',
    position: 'CB',
    classYear: "'26",
    school: 'Birmingham',
    state: 'AL',
    pool: 'HIGH_SCHOOL',
    height: '6-1',
    weight: 185,
    gpa: 3.3,
    paiScore: 93,
    tier: 'ELITE',
    performance: 93,
    athleticism: 95,
    intangibles: 91,
    nationalRank: 9,
    stateRank: 1,
    positionRank: 1,
    trend: 'STEADY',
    nilEstimate: '$2.3M',
    scoutMemo: 'Long, rangy corner with track speed. Two-sport star who uses length to disrupt at the catch point. Ohio State commit.',
    tags: ['5-Star', 'Ohio State Commit', 'Lockdown', 'Track Star'],
    comparisons: ['Sauce Gardner', 'Patrick Surtain II'],
    stats: { interceptions: 8, passBreakups: 22, tackles: 48, forcedFumbles: 3 },
    bullCase: 'Length + speed + ball skills is the trifecta. Ohio State DB room is the NFL pipeline.',
    bearCase: 'Lean frame — needs to add functional weight without losing track speed.',
    mediationVerdict: 'Bull case wins. Elite corners are worth their weight in gold.',
    debateWinner: 'BULL',
    stars: 5,
  },
  {
    firstName: 'Deuce',
    lastName: 'Knight',
    position: 'S',
    classYear: "'26",
    school: 'Alabaster Thompson',
    state: 'AL',
    pool: 'HIGH_SCHOOL',
    height: '6-2',
    weight: 200,
    gpa: 3.5,
    paiScore: 91,
    tier: 'ELITE',
    performance: 91,
    athleticism: 93,
    intangibles: 90,
    nationalRank: 14,
    stateRank: 2,
    positionRank: 1,
    trend: 'UP',
    previousRank: 19,
    nilEstimate: '$1.8M',
    scoutMemo: 'Hard-hitting safety with range. Also played QB in HS showing elite athleticism. Notre Dame commit.',
    tags: ['5-Star', 'Notre Dame Commit', 'Hybrid Safety', 'Athlete'],
    comparisons: ['Derwin James', 'Kyle Hamilton'],
    stats: { interceptions: 6, tackles: 78, sacksAsBlitzer: 4, passBreakups: 14 },
    bullCase: 'Rare athlete who can play safety or nickel. Notre Dame defense is built for this type of versatility.',
    bearCase: 'Position uncertainty — is he a safety, nickel, or linebacker? Needs a defined role.',
    mediationVerdict: 'Bull case wins. Versatility is a feature, not a bug, in modern defense.',
    debateWinner: 'BULL',
    stars: 5,
  },

  // ─── LB ────────────────────────────────────────────────────
  {
    firstName: 'Ty',
    lastName: 'Haywood',
    position: 'LB',
    classYear: "'26",
    school: 'Ryan',
    state: 'TX',
    pool: 'HIGH_SCHOOL',
    height: '6-3',
    weight: 230,
    gpa: 3.6,
    paiScore: 91,
    tier: 'ELITE',
    performance: 92,
    athleticism: 91,
    intangibles: 90,
    nationalRank: 15,
    stateRank: 5,
    positionRank: 1,
    trend: 'STEADY',
    nilEstimate: '$1.7M',
    scoutMemo: 'Downhill thumper with sideline-to-sideline range. Three-down LB who excels in run defense. Texas A&M commit.',
    tags: ['5-Star', 'Texas A&M Commit', 'Linebacker', 'Run Stopper'],
    comparisons: ['Roquan Smith', 'Devin White'],
    stats: { tackles: 148, TFLs: 24, sacks: 8, forcedFumbles: 4 },
    bullCase: 'True 3-down LB with range. A&M defense immediately gets a thumper in the middle.',
    bearCase: 'Coverage skills need refinement against athletic TEs and RBs in space.',
    mediationVerdict: 'Bull case edges it. Elite run defense + improving coverage = complete LB.',
    debateWinner: 'BULL',
    stars: 5,
  },

  // ─── TE ────────────────────────────────────────────────────
  {
    firstName: 'Brody',
    lastName: 'Foley',
    position: 'TE',
    classYear: "'26",
    school: 'Anderson',
    state: 'OH',
    pool: 'HIGH_SCHOOL',
    height: '6-5',
    weight: 240,
    gpa: 3.7,
    paiScore: 90,
    tier: 'ELITE',
    performance: 90,
    athleticism: 91,
    intangibles: 90,
    nationalRank: 18,
    stateRank: 2,
    positionRank: 1,
    trend: 'UP',
    previousRank: 25,
    nilEstimate: '$1.5M',
    scoutMemo: 'Athletic mismatch TE with reliable hands and inline blocking ability. Ohio State commit adds dynamic weapon.',
    tags: ['4-Star', 'Ohio State Commit', 'Tight End', 'Matchup Nightmare'],
    comparisons: ['Kyle Pitts', 'George Kittle'],
    stats: { receptions: 52, receivingYards: 920, receivingTDs: 14, yardsPerCatch: 17.7 },
    bullCase: 'TE is the new premium position. His combination of size, speed, and hands is rare in HS.',
    bearCase: 'TE development timeline is long — may not contribute heavily until Year 2.',
    mediationVerdict: 'Bull case wins. Ohio State needs a TE weapon, and he fits perfectly.',
    debateWinner: 'BULL',
    stars: 4,
  },

  // ─── DT / Interior DL ──────────────────────────────────────
  {
    firstName: 'David',
    lastName: 'Stone',
    position: 'DT',
    classYear: "'26",
    school: 'Oklahoma City Ada',
    state: 'OK',
    pool: 'HIGH_SCHOOL',
    height: '6-4',
    weight: 295,
    gpa: 3.2,
    paiScore: 92,
    tier: 'ELITE',
    performance: 93,
    athleticism: 92,
    intangibles: 90,
    nationalRank: 11,
    stateRank: 1,
    positionRank: 1,
    trend: 'STEADY',
    nilEstimate: '$2.0M',
    scoutMemo: 'Interior disruptor with elite quickness for his size. Collapses the pocket consistently. Oklahoma commit.',
    tags: ['5-Star', 'Oklahoma Commit', 'Interior Pressure', 'Anchor'],
    comparisons: ['Quinnen Williams', 'Chris Jones'],
    stats: { sacks: 14, TFLs: 28, tackles: 72, forcedFumbles: 5 },
    bullCase: 'Interior pass rush wins championships. His first-step quickness at 295 lbs is absurd.',
    bearCase: 'Oklahoma defensive development has been inconsistent in recent years.',
    mediationVerdict: 'Bull case wins. Elite DTs are scheme-proof and he is the best in the class.',
    debateWinner: 'BULL',
    stars: 5,
  },

  // ─── ATH / Utility ─────────────────────────────────────────
  {
    firstName: 'DJ',
    lastName: 'Pickett',
    position: 'ATH',
    classYear: "'26",
    school: 'Zephyrhills',
    state: 'FL',
    pool: 'HIGH_SCHOOL',
    height: '6-2',
    weight: 195,
    gpa: 3.4,
    paiScore: 90,
    tier: 'ELITE',
    performance: 91,
    athleticism: 92,
    intangibles: 88,
    nationalRank: 16,
    stateRank: 2,
    positionRank: 1,
    trend: 'UP',
    previousRank: 22,
    nilEstimate: '$1.6M',
    scoutMemo: 'Rare two-way athlete who plays WR and CB. Electric with the ball in his hands. Georgia commit.',
    tags: ['5-Star', 'Georgia Commit', 'Two-Way', 'Versatile'],
    comparisons: ['Champ Bailey', 'Charles Woodson'],
    stats: { receptions: 48, receivingYards: 980, receivingTDs: 14, interceptions: 5, passBreakups: 12 },
    bullCase: 'Kirby Smart loves versatile athletes. Could contribute on both sides of the ball immediately.',
    bearCase: 'Needs to pick a side — trying to do both in college rarely works long-term.',
    mediationVerdict: 'Bull case wins. Start at CB, use on offense in packages. Georgia maximizes talent.',
    debateWinner: 'BULL',
    stars: 5,
  },

  // ─── 4-STAR Blue Chip Recruits ─────────────────────────────
  {
    firstName: 'Jared',
    lastName: 'Curtis',
    position: 'QB',
    classYear: "'26",
    school: 'Roswell',
    state: 'GA',
    pool: 'HIGH_SCHOOL',
    height: '6-3',
    weight: 205,
    gpa: 3.6,
    paiScore: 88,
    tier: 'BLUE_CHIP',
    performance: 89,
    athleticism: 87,
    intangibles: 88,
    nationalRank: 28,
    stateRank: 3,
    positionRank: 5,
    trend: 'UP',
    previousRank: 38,
    nilEstimate: '$1.2M',
    scoutMemo: 'Polished passer from Georgia pipeline. Quick release and good pocket feel. Alabama commit.',
    tags: ['4-Star', 'Alabama Commit', 'Pocket Passer', 'Rising'],
    comparisons: ['Mac Jones', 'Kirk Cousins'],
    stats: { passingYards: 3200, passingTDs: 36, rushingYards: 280, completionPct: '66.2%' },
    bullCase: 'Alabama QB room needs a franchise arm. His accuracy and timing are elite for a HS QB.',
    bearCase: 'Not a dual-threat — modern CFB increasingly demands mobility from QBs.',
    mediationVerdict: 'Balanced. Pocket passers still thrive in the right system. Alabama fits.',
    debateWinner: 'BULL',
    stars: 4,
  },
  {
    firstName: 'Elijah',
    lastName: 'Griffin',
    position: 'EDGE',
    classYear: "'26",
    school: 'Gardendale',
    state: 'AL',
    pool: 'HIGH_SCHOOL',
    height: '6-4',
    weight: 250,
    gpa: 3.3,
    paiScore: 89,
    tier: 'BLUE_CHIP',
    performance: 90,
    athleticism: 89,
    intangibles: 87,
    nationalRank: 22,
    stateRank: 3,
    positionRank: 3,
    trend: 'STEADY',
    nilEstimate: '$1.5M',
    scoutMemo: 'Explosive edge with bend and power. Alabama legacy recruit who fits their defensive DNA. Alabama commit.',
    tags: ['4-Star', 'Alabama Commit', 'Edge Rusher', 'High Motor'],
    comparisons: ['Will Anderson Jr.', 'Dallas Turner'],
    stats: { sacks: 16, TFLs: 30, forcedFumbles: 6, tackles: 88 },
    bullCase: 'Alabama develops edge rushers better than anyone. His motor and skill set fit the mold perfectly.',
    bearCase: 'Deep EDGE class — may redshirt behind veterans.',
    mediationVerdict: 'Bull case wins. Patience + Alabama development = NFL pass rusher.',
    debateWinner: 'BULL',
    stars: 4,
  },
  {
    firstName: 'Immanuel',
    lastName: 'Iheanacho',
    position: 'DT',
    classYear: "'26",
    school: 'Spring Westfield',
    state: 'TX',
    pool: 'HIGH_SCHOOL',
    height: '6-4',
    weight: 305,
    gpa: 3.2,
    paiScore: 89,
    tier: 'BLUE_CHIP',
    performance: 90,
    athleticism: 88,
    intangibles: 88,
    nationalRank: 24,
    stateRank: 6,
    positionRank: 2,
    trend: 'UP',
    previousRank: 32,
    nilEstimate: '$1.4M',
    scoutMemo: 'Powerful interior lineman with quick hands. Space-eater who also gets push up the middle. Texas A&M commit.',
    tags: ['4-Star', 'Texas A&M Commit', 'Nose Tackle', 'Run Stuffer'],
    comparisons: ['DeForest Buckner', 'Vita Vea'],
    stats: { sacks: 10, TFLs: 22, tackles: 68, forcedFumbles: 3 },
    bullCase: 'A&M DL room is stacking talent. His power and pad level are college-ready right now.',
    bearCase: 'Not a dynamic pass rusher yet — primarily a run defender at this stage.',
    mediationVerdict: 'Bull case edges it. Run defense anchors win SEC games, and pass rush will develop.',
    debateWinner: 'BULL',
    stars: 4,
  },
  {
    firstName: 'Justus',
    lastName: 'Terry',
    position: 'DT',
    classYear: "'26",
    school: 'Manchester',
    state: 'GA',
    pool: 'HIGH_SCHOOL',
    height: '6-5',
    weight: 290,
    gpa: 3.1,
    paiScore: 88,
    tier: 'BLUE_CHIP',
    performance: 89,
    athleticism: 88,
    intangibles: 86,
    nationalRank: 26,
    stateRank: 4,
    positionRank: 3,
    trend: 'STEADY',
    nilEstimate: '$1.3M',
    scoutMemo: 'Long, disruptive DT who can play 3-tech or 5-tech. Versatile defensive lineman. Georgia commit.',
    tags: ['4-Star', 'Georgia Commit', 'Versatile DL', 'High Ceiling'],
    comparisons: ['Travon Walker', 'Jordan Davis'],
    stats: { sacks: 12, TFLs: 26, tackles: 75, forcedFumbles: 4 },
    bullCase: 'Georgia DL factory continues. His length and motor project to a multi-year starter.',
    bearCase: 'Tweener size — not quite a true NT, not quite an edge. Needs a position.',
    mediationVerdict: 'Bull case wins. Georgia will find the right spot for this much talent.',
    debateWinner: 'BULL',
    stars: 4,
  },
];
