'use client';

/**
 * Per|Form Content Feed — Articles, Podcasts, Debates, Rankings
 *
 * Public content generated by the War Room pipeline.
 * Scouting reports, Bull vs Bear recaps, ranking updates, and editorials.
 */

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { motion } from 'framer-motion';
import {
  ArrowUpRight,
  FileText,
  Headphones,
  TrendingUp,
  Swords,
  ClipboardList,
} from 'lucide-react';
import type { ContentArticle, ContentType } from '@/lib/perform/types';
import { CONTENT_TYPE_STYLES } from '@/lib/perform/types';
import { staggerContainer, staggerItem } from '@/lib/motion/variants';

const TYPE_ICONS: Record<ContentType, typeof FileText> = {
  BLOG: FileText,
  PODCAST: Headphones,
  RANKING_UPDATE: TrendingUp,
  SCOUTING_REPORT: ClipboardList,
  DEBATE_RECAP: Swords,
};

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });
}

export default function ContentFeedPage() {
  const [articles, setArticles] = useState<ContentArticle[]>([]);
  const [loading, setLoading] = useState(true);
  const [typeFilter, setTypeFilter] = useState<string>('ALL');

  useEffect(() => {
    fetch('/api/perform/content')
      .then(res => res.json())
      .then(data => {
        setArticles(Array.isArray(data) ? data : []);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, []);

  const types = ['ALL', ...Array.from(new Set(articles.map(a => a.type)))];

  const filtered = typeFilter === 'ALL'
    ? articles
    : articles.filter(a => a.type === typeFilter);

  return (
    <motion.div
      variants={staggerContainer}
      initial="hidden"
      animate="visible"
      className="max-w-4xl mx-auto px-4 md:px-6 lg:px-8 py-10 space-y-8"
    >
      {/* Header */}
      <motion.div variants={staggerItem} className="space-y-4">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-400/10 border border-blue-400/20">
            <FileText size={20} className="text-blue-400" />
          </div>
          <div>
            <h1 className="text-2xl md:text-3xl font-display text-slate-800 tracking-tight">
              Content Feed
            </h1>
            <p className="text-xs text-slate-400 font-mono">
              Scouting Reports &middot; Debates &middot; Rankings &middot; Analysis
            </p>
          </div>
        </div>
      </motion.div>

      {/* Type Filters */}
      <motion.div variants={staggerItem} className="flex gap-2 overflow-x-auto pb-1">
        {types.map(type => {
          const style = type === 'ALL' ? null : CONTENT_TYPE_STYLES[type as ContentType];
          return (
            <button
              key={type}
              onClick={() => setTypeFilter(type)}
              className={`px-3 py-1.5 rounded-lg text-xs font-mono transition-colors whitespace-nowrap ${
                typeFilter === type
                  ? style
                    ? `${style.bg} ${style.color} border border-current/20`
                    : 'bg-gold/15 text-gold border border-gold/30'
                  : 'bg-white text-slate-400 border border-slate-200 hover:text-slate-500'
              }`}
            >
              {type === 'ALL' ? 'All' : style?.label || type}
            </button>
          );
        })}
      </motion.div>

      {/* Articles */}
      {loading ? (
        <div className="text-center py-20">
          <div className="inline-block h-6 w-6 border-2 border-gold/30 border-t-gold rounded-full animate-spin" />
          <p className="text-xs text-slate-400 mt-3 font-mono">Loading content...</p>
        </div>
      ) : (
        <div className="space-y-4">
          {filtered.map(article => {
            const typeStyle = CONTENT_TYPE_STYLES[article.type];
            const Icon = TYPE_ICONS[article.type];

            return (
              <motion.article
                key={article.id}
                variants={staggerItem}
                className="wireframe-card rounded-2xl p-5 md:p-6 hover:border-gold/10 transition-colors group"
              >
                <div className="flex flex-col md:flex-row md:items-start gap-4">
                  {/* Icon */}
                  <div className={`flex-shrink-0 h-10 w-10 rounded-xl ${typeStyle.bg} flex items-center justify-center`}>
                    <Icon size={18} className={typeStyle.color} />
                  </div>

                  {/* Content */}
                  <div className="flex-1 space-y-2">
                    <div className="flex items-center gap-2 flex-wrap">
                      <span className={`text-[0.55rem] font-mono uppercase ${typeStyle.color}`}>
                        {typeStyle.label}
                      </span>
                      <span className="text-slate-300">&middot;</span>
                      <span className="text-[0.55rem] font-mono text-slate-300">
                        {formatDate(article.generatedAt)}
                      </span>
                      <span className="text-slate-300">&middot;</span>
                      <span className="text-[0.55rem] font-mono text-slate-300">
                        {article.readTimeMin} min {article.type === 'PODCAST' ? 'listen' : 'read'}
                      </span>
                    </div>

                    <h2 className="text-base font-medium text-slate-800 group-hover:text-gold transition-colors">
                      {article.title}
                    </h2>

                    <p className="text-sm text-slate-400 leading-relaxed">
                      {article.excerpt}
                    </p>

                    <div className="flex items-center gap-3 pt-1">
                      <span className="text-[0.5rem] font-mono text-slate-300 uppercase">
                        by {article.generatedBy}
                      </span>
                      {article.prospectId && (
                        <Link
                          href={`/perform/prospects/${article.prospectName?.toLowerCase().replace(/\s+/g, '-')}`}
                          className="flex items-center gap-1 text-[0.55rem] font-mono text-gold/50 hover:text-gold transition-colors"
                        >
                          {article.prospectName}
                          <ArrowUpRight size={10} />
                        </Link>
                      )}
                    </div>
                  </div>
                </div>
              </motion.article>
            );
          })}

          {filtered.length === 0 && (
            <div className="text-center py-12 text-slate-300 text-sm">
              No content matches this filter.
            </div>
          )}
        </div>
      )}
    </motion.div>
  );
}
