'use client';

/**
 * Per|Form Mock Draft View
 *
 * Full round-by-round mock draft display with team needs,
 * prospect grades, and pick rationale.
 */

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { motion, AnimatePresence } from 'framer-motion';
import { ArrowLeft, BarChart3, ChevronDown, ChevronRight, Radio } from 'lucide-react';
import { DRAFT_TIER_STYLES, getScoreColor } from '@/lib/perform/types';
import type { DraftTier } from '@/lib/perform/types';
import { MockDraftSet } from '@/components/perform/broadcast/shows/MockDraftSet';
import { NetworkBug } from '@/components/perform/broadcast/graphics';
import type { BroadcastSegment } from '@/components/perform/broadcast/engine';

const staggerContainer = {
  hidden: { opacity: 0 },
  visible: { opacity: 1, transition: { staggerChildren: 0.04 } },
};
const staggerItem = {
  hidden: { opacity: 0, y: 10 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.3 } },
};

export default function MockDraftPage() {
  const [mockDraft, setMockDraft] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [expandedPick, setExpandedPick] = useState<string | null>(null);
  const [roundFilter, setRoundFilter] = useState<number>(0); // 0 = all
  const [showOnTheClock, setShowOnTheClock] = useState(true);

  const mockDraftSegment: BroadcastSegment = {
    id: 'mock-draft-otc',
    type: 'MOCK_DRAFT_DESK',
    title: `NFL Draft ${new Date().getFullYear()}`,
    durationSeconds: 30,
    host: 'BOOMER_ANG',
    topic: 'On The Clock — Round 1 Projections',
  };

  useEffect(() => {
    fetch('/api/perform/draft?mock=latest')
      .then(r => r.json())
      .then(data => {
        if (data && !data.error) setMockDraft(data);
      })
      .catch(console.error)
      .finally(() => setLoading(false));
  }, []);

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[50vh] gap-3">
        <div className="h-8 w-8 border-2 border-gold/30 border-t-gold rounded-full animate-spin" />
        <span className="text-xs font-mono text-slate-400">Loading Mock Draft...</span>
      </div>
    );
  }

  if (!mockDraft || !mockDraft.picks) {
    return (
      <div className="max-w-6xl mx-auto px-6 py-10 space-y-6">
        <Link
          href="/perform/draft"
          className="inline-flex items-center gap-1.5 text-xs text-slate-400 hover:text-gold font-mono uppercase tracking-wider transition-colors"
        >
          <ArrowLeft className="h-3 w-3" />
          Draft Hub
        </Link>
        <div className="wireframe-card rounded-2xl p-8 text-center">
          <BarChart3 className="h-8 w-8 text-gold/30 mx-auto mb-3" />
          <p className="text-sm text-slate-400">No mock draft generated yet.</p>
          <p className="text-xs text-slate-300 mt-1">Go to Draft Hub and click &quot;New Mock Draft&quot; to generate one.</p>
        </div>
      </div>
    );
  }

  const picks = roundFilter > 0
    ? mockDraft.picks.filter((p: any) => p.round === roundFilter)
    : mockDraft.picks;

  const rounds = Array.from(new Set<number>(mockDraft.picks.map((p: any) => p.round))).sort((a, b) => a - b);

  return (
    <motion.div
      className="max-w-6xl mx-auto px-6 py-10 space-y-8"
      variants={staggerContainer}
      initial="hidden"
      animate="visible"
    >
      <motion.div variants={staggerItem}>
        <Link
          href="/perform/draft"
          className="inline-flex items-center gap-1.5 text-xs text-slate-400 hover:text-gold font-mono uppercase tracking-wider transition-colors"
        >
          <ArrowLeft className="h-3 w-3" />
          Draft Hub
        </Link>
      </motion.div>

      <motion.div variants={staggerItem} className="flex items-end justify-between">
        <div>
          <h1 className="text-2xl md:text-3xl font-display text-slate-800 tracking-tight">
            {mockDraft.title}
          </h1>
          <p className="text-sm text-slate-400 mt-1">
            {mockDraft.picks.length} picks across {rounds.length} rounds — generated by Per|Form Engine
          </p>
        </div>
        <button
          onClick={() => setShowOnTheClock(!showOnTheClock)}
          className={`flex items-center gap-2 px-3 py-1.5 rounded-full border text-[0.6rem] font-bold tracking-[0.2em] uppercase transition-all ${
            showOnTheClock
              ? 'bg-red-600/10 text-red-500 border-red-500/40 hover:bg-red-600/20'
              : 'bg-gold/10 text-gold border-gold/30 hover:bg-gold/20'
          }`}
        >
          <Radio size={12} className={showOnTheClock ? 'animate-pulse text-red-500' : 'text-gold'} />
          {showOnTheClock ? 'Hide Broadcast' : 'On The Clock'}
        </button>
      </motion.div>

      {/* Broadcast "On The Clock" Preview */}
      <AnimatePresence>
        {showOnTheClock && (
          <motion.div
            variants={staggerItem}
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: 'auto' }}
            exit={{ opacity: 0, height: 0 }}
            transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
            className="overflow-hidden"
          >
            <div className="relative bg-white border border-gold/20 rounded-2xl overflow-hidden shadow-[0_0_40px_rgba(218,165,32,0.06)]">
              {/* Network Bug overlay */}
              <div className="absolute top-4 right-4 z-20 scale-75 origin-top-right pointer-events-none">
                <NetworkBug />
              </div>

              {/* Broadcast header bar */}
              <div className="flex items-center gap-2 px-5 py-2.5 bg-[#F8FAFC] border-b border-slate-100">
                <div className="h-2 w-2 bg-red-500 rounded-full animate-pulse" />
                <span className="text-[0.55rem] font-mono uppercase tracking-[0.25em] text-gold font-bold">Live Broadcast</span>
                <span className="text-[0.55rem] font-mono uppercase tracking-[0.15em] text-slate-400 ml-auto">On The Clock</span>
              </div>

              {/* MockDraftSet in a contained preview */}
              <div className="h-[400px] overflow-hidden">
                <MockDraftSet segment={mockDraftSegment} />
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Round filters */}
      <motion.div variants={staggerItem} className="flex gap-1.5 overflow-x-auto pb-1">
        <button
          onClick={() => setRoundFilter(0)}
          className={`px-3 py-1.5 text-xs font-mono rounded-lg border transition-colors ${
            roundFilter === 0
              ? 'bg-gold/15 text-gold border-gold/30'
              : 'bg-white text-slate-400 border-slate-100 hover:border-slate-200'
          }`}
        >
          All Rounds
        </button>
        {rounds.map((r: number) => (
          <button
            key={r}
            onClick={() => setRoundFilter(r)}
            className={`px-3 py-1.5 text-xs font-mono rounded-lg border transition-colors ${
              roundFilter === r
                ? 'bg-gold/15 text-gold border-gold/30'
                : 'bg-white text-slate-400 border-slate-100 hover:border-slate-200'
            }`}
          >
            Round {r}
          </button>
        ))}
      </motion.div>

      {/* Picks list */}
      <motion.div variants={staggerItem} className="wireframe-card rounded-2xl overflow-hidden">
        {picks.map((pick: any) => {
          const prospect = pick.prospect;
          const tierStyle = DRAFT_TIER_STYLES[prospect?.tier as DraftTier] || DRAFT_TIER_STYLES.DAY_3;
          const isExpanded = expandedPick === pick.id;

          return (
            <div key={pick.id} className="border-b border-slate-200 last:border-b-0">
              <button
                onClick={() => setExpandedPick(isExpanded ? null : pick.id)}
                className="w-full flex items-center gap-3 px-4 py-3 hover:bg-white transition-colors text-left"
              >
                {/* Pick number */}
                <div className="flex flex-col items-center w-12 shrink-0">
                  <span className="text-lg font-mono font-bold text-slate-500">
                    {pick.overall}
                  </span>
                  <span className="text-[0.5rem] font-mono text-slate-300">
                    R{pick.round}P{pick.pickInRound}
                  </span>
                </div>

                {/* Team */}
                <div className="w-32 shrink-0">
                  <span className="text-xs text-slate-600 block truncate">{pick.teamName}</span>
                </div>

                {/* Position badge */}
                <span className={`text-[0.6rem] font-mono px-1.5 py-0.5 rounded ${tierStyle.bg} ${tierStyle.border} ${tierStyle.text} border shrink-0`}>
                  {prospect?.position}
                </span>

                {/* Prospect name */}
                <div className="flex-1 min-w-0">
                  <span className="text-sm text-slate-800 font-medium">
                    {prospect?.firstName} {prospect?.lastName}
                  </span>
                  <span className="text-xs text-slate-400 ml-2 hidden sm:inline">
                    {prospect?.college}
                  </span>
                </div>

                {/* P.A.I. */}
                <span className={`text-sm font-mono font-bold ${getScoreColor(prospect?.paiScore || 0)} shrink-0`}>
                  {prospect?.paiScore}
                </span>

                {/* Fit score */}
                {pick.fitScore && (
                  <div className="hidden sm:flex flex-col items-center w-12 shrink-0">
                    <span className="text-[0.5rem] font-mono text-slate-300">FIT</span>
                    <span className={`text-xs font-mono ${getScoreColor(pick.fitScore)}`}>
                      {pick.fitScore}
                    </span>
                  </div>
                )}

                {/* Expand icon */}
                {isExpanded
                  ? <ChevronDown className="h-4 w-4 text-slate-300 shrink-0" />
                  : <ChevronRight className="h-4 w-4 text-slate-300 shrink-0" />
                }
              </button>

              {/* Expanded details */}
              {isExpanded && prospect && (
                <div className="px-4 pb-4 pl-16 space-y-3">
                  <div className="grid grid-cols-3 gap-3">
                    <div className="bg-white border border-slate-100 rounded-xl p-3">
                      <div className="text-[0.5rem] font-mono text-slate-400 uppercase mb-1">Performance</div>
                      <div className={`text-lg font-mono font-bold ${getScoreColor(prospect.performance)}`}>
                        {prospect.performance}
                      </div>
                    </div>
                    <div className="bg-white border border-slate-100 rounded-xl p-3">
                      <div className="text-[0.5rem] font-mono text-slate-400 uppercase mb-1">Athleticism</div>
                      <div className={`text-lg font-mono font-bold ${getScoreColor(prospect.athleticism)}`}>
                        {prospect.athleticism}
                      </div>
                    </div>
                    <div className="bg-white border border-slate-100 rounded-xl p-3">
                      <div className="text-[0.5rem] font-mono text-slate-400 uppercase mb-1">Intangibles</div>
                      <div className={`text-lg font-mono font-bold ${getScoreColor(prospect.intangibles)}`}>
                        {prospect.intangibles}
                      </div>
                    </div>
                  </div>

                  {pick.rationale && (
                    <div className="bg-white border border-slate-100 rounded-xl p-3">
                      <div className="text-[0.5rem] font-mono text-slate-400 uppercase mb-1">Pick Rationale</div>
                      <p className="text-xs text-slate-500">{pick.rationale}</p>
                    </div>
                  )}

                  {prospect.scoutMemo && (
                    <div className="bg-white border border-slate-100 rounded-xl p-3">
                      <div className="text-[0.5rem] font-mono text-slate-400 uppercase mb-1">Scout Memo</div>
                      <p className="text-xs text-slate-500">{prospect.scoutMemo}</p>
                    </div>
                  )}

                  <div className="flex gap-2 flex-wrap">
                    <span className="text-[0.55rem] font-mono text-slate-400">
                      {prospect.height} / {prospect.weight} lbs
                    </span>
                    <span className="text-[0.55rem] font-mono text-slate-400">
                      {prospect.college} ({prospect.conference})
                    </span>
                    <span className={`text-[0.55rem] font-mono ${tierStyle.text}`}>
                      {tierStyle.label}
                    </span>
                  </div>
                </div>
              )}
            </div>
          );
        })}
      </motion.div>
    </motion.div>
  );
}
